"""Generate remaining categories for vocabulary."""

# PROP (150 concepts)
PROP = [
    # STATE (20)
    ("PROP.STATE.ACTIVE", "STATE", "Active or enabled", ["active", "enabled", "on"]),
    ("PROP.STATE.INACTIVE", "STATE", "Inactive or disabled", ["inactive", "disabled", "off"]),
    ("PROP.STATE.PENDING", "STATE", "Pending or waiting", ["pending", "waiting", "queued"]),
    ("PROP.STATE.COMPLETE", "STATE", "Completed", ["complete", "done", "finished"]),
    ("PROP.STATE.ERROR", "STATE", "Error state", ["error", "failed", "broken"]),
    ("PROP.STATE.RUNNING", "STATE", "Currently running", ["executing", "processing"]),
    ("PROP.STATE.STOPPED", "STATE", "Stopped", ["halted", "terminated"]),
    ("PROP.STATE.PAUSED", "STATE", "Paused", ["suspended", "frozen"]),
    ("PROP.STATE.STARTING", "STATE", "Starting up", ["initializing", "booting"]),
    ("PROP.STATE.STOPPING", "STATE", "Shutting down", ["terminating", "closing"]),
    ("PROP.STATE.DEGRADED", "STATE", "Degraded performance", ["impaired", "limited"]),
    ("PROP.STATE.HEALTHY", "STATE", "Healthy state", ["ok", "normal"]),
    ("PROP.STATE.UNHEALTHY", "STATE", "Unhealthy state", ["sick", "failing"]),
    ("PROP.STATE.READY", "STATE", "Ready for use", ["available", "prepared"]),
    ("PROP.STATE.BUSY", "STATE", "Busy or occupied", ["occupied", "working"]),
    ("PROP.STATE.IDLE", "STATE", "Idle or free", ["free", "unused"]),
    ("PROP.STATE.LOCKED", "STATE", "Locked state", ["held", "acquired"]),
    ("PROP.STATE.UNLOCKED", "STATE", "Unlocked state", ["free", "released"]),
    ("PROP.STATE.CONNECTED", "STATE", "Connected", ["online", "linked"]),
    ("PROP.STATE.DISCONNECTED", "STATE", "Disconnected", ["offline", "unlinked"]),
    # QUALITY (15)
    ("PROP.QUALITY.HIGH", "QUALITY", "High quality", ["excellent", "premium"]),
    ("PROP.QUALITY.MEDIUM", "QUALITY", "Medium quality", ["average", "standard"]),
    ("PROP.QUALITY.LOW", "QUALITY", "Low quality", ["poor", "inferior"]),
    ("PROP.QUALITY.VERIFIED", "QUALITY", "Verified quality", ["certified", "checked"]),
    ("PROP.QUALITY.UNVERIFIED", "QUALITY", "Unverified quality", ["unchecked", "unknown"]),
    ("PROP.QUALITY.TRUSTED", "QUALITY", "Trusted source", ["reliable", "proven"]),
    ("PROP.QUALITY.UNTRUSTED", "QUALITY", "Untrusted source", ["suspicious", "unknown"]),
    ("PROP.QUALITY.ACCURATE", "QUALITY", "Accurate result", ["precise", "exact"]),
    ("PROP.QUALITY.APPROXIMATE", "QUALITY", "Approximate result", ["rough", "estimated"]),
    ("PROP.QUALITY.COMPLETE", "QUALITY", "Complete data", ["full", "whole"]),
    ("PROP.QUALITY.PARTIAL", "QUALITY", "Partial data", ["incomplete", "fragment"]),
    ("PROP.QUALITY.FRESH", "QUALITY", "Fresh or recent", ["current", "new"]),
    ("PROP.QUALITY.STALE", "QUALITY", "Stale or outdated", ["old", "expired"]),
    ("PROP.QUALITY.STABLE", "QUALITY", "Stable version", ["production", "release"]),
    ("PROP.QUALITY.EXPERIMENTAL", "QUALITY", "Experimental version", ["beta", "preview"]),
    # SIZE (15)
    ("PROP.SIZE.LARGE", "SIZE", "Large size", ["big", "huge", "massive"]),
    ("PROP.SIZE.MEDIUM", "SIZE", "Medium size", ["average", "standard"]),
    ("PROP.SIZE.SMALL", "SIZE", "Small size", ["tiny", "little", "mini"]),
    ("PROP.SIZE.EMPTY", "SIZE", "Empty or zero size", ["none", "null"]),
    ("PROP.SIZE.UNLIMITED", "SIZE", "Unlimited size", ["infinite", "unbounded"]),
    ("PROP.SIZE.FIXED", "SIZE", "Fixed size", ["constant", "static"]),
    ("PROP.SIZE.VARIABLE", "SIZE", "Variable size", ["dynamic", "flexible"]),
    ("PROP.SIZE.GROWING", "SIZE", "Growing size", ["expanding", "increasing"]),
    ("PROP.SIZE.SHRINKING", "SIZE", "Shrinking size", ["decreasing", "reducing"]),
    ("PROP.SIZE.BYTES", "SIZE", "Size in bytes", ["b", "octets"]),
    ("PROP.SIZE.KILOBYTES", "SIZE", "Size in kilobytes", ["kb", "kibibytes"]),
    ("PROP.SIZE.MEGABYTES", "SIZE", "Size in megabytes", ["mb", "mibibytes"]),
    ("PROP.SIZE.GIGABYTES", "SIZE", "Size in gigabytes", ["gb", "gibibytes"]),
    ("PROP.SIZE.TERABYTES", "SIZE", "Size in terabytes", ["tb", "tebibytes"]),
    ("PROP.SIZE.COUNT", "SIZE", "Count or quantity", ["number", "total"]),
    # PRIORITY (10)
    ("PROP.PRIORITY.CRITICAL", "PRIORITY", "Critical priority", ["p0", "emergency"]),
    ("PROP.PRIORITY.HIGH", "PRIORITY", "High priority", ["urgent", "important"]),
    ("PROP.PRIORITY.MEDIUM", "PRIORITY", "Medium priority", ["normal", "standard"]),
    ("PROP.PRIORITY.LOW", "PRIORITY", "Low priority", ["minor", "trivial"]),
    ("PROP.PRIORITY.BACKGROUND", "PRIORITY", "Background priority", ["deferred", "lazy"]),
    ("PROP.PRIORITY.REALTIME", "PRIORITY", "Real-time priority", ["immediate", "instant"]),
    ("PROP.PRIORITY.BATCH", "PRIORITY", "Batch priority", ["bulk", "queued"]),
    ("PROP.PRIORITY.SCHEDULED", "PRIORITY", "Scheduled priority", ["planned", "timed"]),
    ("PROP.PRIORITY.INTERACTIVE", "PRIORITY", "Interactive priority", ["user-facing"]),
    ("PROP.PRIORITY.SYSTEM", "PRIORITY", "System priority", ["infrastructure"]),
    # DETAIL (10)
    ("PROP.DETAIL.HIGH", "DETAIL", "High detail", ["verbose", "comprehensive"]),
    ("PROP.DETAIL.MEDIUM", "DETAIL", "Medium detail", ["standard", "normal"]),
    ("PROP.DETAIL.LOW", "DETAIL", "Low detail", ["brief", "summary"]),
    ("PROP.DETAIL.MINIMAL", "DETAIL", "Minimal detail", ["bare", "essential"]),
    ("PROP.DETAIL.FULL", "DETAIL", "Full detail", ["complete", "exhaustive"]),
    ("PROP.DETAIL.DEBUG", "DETAIL", "Debug level detail", ["trace", "diagnostic"]),
    ("PROP.DETAIL.METADATA", "DETAIL", "Metadata only", ["headers", "info"]),
    ("PROP.DETAIL.PREVIEW", "DETAIL", "Preview level", ["thumbnail", "snippet"]),
    ("PROP.DETAIL.RAW", "DETAIL", "Raw unprocessed", ["original", "source"]),
    ("PROP.DETAIL.FORMATTED", "DETAIL", "Formatted output", ["rendered", "styled"]),
    # TYPE (15)
    ("PROP.TYPE.SYNC", "TYPE", "Synchronous", ["blocking", "immediate"]),
    ("PROP.TYPE.ASYNC", "TYPE", "Asynchronous", ["nonblocking", "deferred"]),
    ("PROP.TYPE.STREAMING", "TYPE", "Streaming mode", ["continuous", "realtime"]),
    ("PROP.TYPE.BATCH", "TYPE", "Batch mode", ["bulk", "grouped"]),
    ("PROP.TYPE.ONESHOT", "TYPE", "One-shot operation", ["single", "once"]),
    ("PROP.TYPE.RECURRING", "TYPE", "Recurring operation", ["periodic", "repeated"]),
    ("PROP.TYPE.TRANSIENT", "TYPE", "Transient data", ["temporary", "ephemeral"]),
    ("PROP.TYPE.PERSISTENT", "TYPE", "Persistent data", ["durable", "permanent"]),
    ("PROP.TYPE.CACHED", "TYPE", "Cached data", ["buffered", "stored"]),
    ("PROP.TYPE.COMPUTED", "TYPE", "Computed value", ["calculated", "derived"]),
    ("PROP.TYPE.MUTABLE", "TYPE", "Mutable data", ["changeable", "writable"]),
    ("PROP.TYPE.IMMUTABLE", "TYPE", "Immutable data", ["readonly", "frozen"]),
    ("PROP.TYPE.PUBLIC", "TYPE", "Public access", ["open", "shared"]),
    ("PROP.TYPE.PRIVATE", "TYPE", "Private access", ["restricted", "internal"]),
    ("PROP.TYPE.PROTECTED", "TYPE", "Protected access", ["guarded", "limited"]),
    # PERFORMANCE (15)
    ("PROP.PERF.FAST", "PERFORMANCE", "Fast performance", ["quick", "rapid"]),
    ("PROP.PERF.SLOW", "PERFORMANCE", "Slow performance", ["sluggish", "delayed"]),
    ("PROP.PERF.OPTIMAL", "PERFORMANCE", "Optimal performance", ["best", "peak"]),
    ("PROP.PERF.DEGRADED", "PERFORMANCE", "Degraded performance", ["reduced", "impaired"]),
    ("PROP.PERF.LATENCY.LOW", "PERFORMANCE", "Low latency", ["quick response"]),
    ("PROP.PERF.LATENCY.HIGH", "PERFORMANCE", "High latency", ["slow response"]),
    ("PROP.PERF.THROUGHPUT.HIGH", "PERFORMANCE", "High throughput", ["fast", "efficient"]),
    ("PROP.PERF.THROUGHPUT.LOW", "PERFORMANCE", "Low throughput", ["bottleneck"]),
    ("PROP.PERF.CPU.HIGH", "PERFORMANCE", "High CPU usage", ["intensive", "heavy"]),
    ("PROP.PERF.CPU.LOW", "PERFORMANCE", "Low CPU usage", ["lightweight", "efficient"]),
    ("PROP.PERF.MEMORY.HIGH", "PERFORMANCE", "High memory usage", ["intensive"]),
    ("PROP.PERF.MEMORY.LOW", "PERFORMANCE", "Low memory usage", ["efficient"]),
    ("PROP.PERF.IO.HIGH", "PERFORMANCE", "High I/O usage", ["disk-heavy"]),
    ("PROP.PERF.IO.LOW", "PERFORMANCE", "Low I/O usage", ["lightweight"]),
    ("PROP.PERF.NETWORK.HIGH", "PERFORMANCE", "High network usage", ["bandwidth-heavy"]),
    # CONFIDENCE (10)
    ("PROP.CONFIDENCE.CERTAIN", "CONFIDENCE", "Certain result", ["definite", "100%"]),
    ("PROP.CONFIDENCE.HIGH", "CONFIDENCE", "High confidence", ["likely", "probable"]),
    ("PROP.CONFIDENCE.MEDIUM", "CONFIDENCE", "Medium confidence", ["possible", "maybe"]),
    ("PROP.CONFIDENCE.LOW", "CONFIDENCE", "Low confidence", ["unlikely", "uncertain"]),
    ("PROP.CONFIDENCE.UNKNOWN", "CONFIDENCE", "Unknown confidence", ["undetermined"]),
    ("PROP.CONFIDENCE.SCORE", "CONFIDENCE", "Numeric score", ["probability", "weight"]),
    ("PROP.CONFIDENCE.THRESHOLD", "CONFIDENCE", "Confidence threshold", ["cutoff", "limit"]),
    ("PROP.CONFIDENCE.CALIBRATED", "CONFIDENCE", "Calibrated estimate", ["adjusted"]),
    ("PROP.CONFIDENCE.PREDICTED", "CONFIDENCE", "Predicted value", ["estimated"]),
    ("PROP.CONFIDENCE.OBSERVED", "CONFIDENCE", "Observed value", ["measured", "actual"]),
    # FORMAT (10)
    ("PROP.FORMAT.TEXT", "FORMAT", "Plain text format", ["txt", "ascii"]),
    ("PROP.FORMAT.JSON", "FORMAT", "JSON format", ["application/json"]),
    ("PROP.FORMAT.BINARY", "FORMAT", "Binary format", ["raw", "bytes"]),
    ("PROP.FORMAT.XML", "FORMAT", "XML format", ["application/xml"]),
    ("PROP.FORMAT.CSV", "FORMAT", "CSV format", ["text/csv"]),
    ("PROP.FORMAT.HTML", "FORMAT", "HTML format", ["text/html"]),
    ("PROP.FORMAT.PROTOBUF", "FORMAT", "Protobuf format", ["proto"]),
    ("PROP.FORMAT.MSGPACK", "FORMAT", "MessagePack format", ["binary json"]),
    ("PROP.FORMAT.AVRO", "FORMAT", "Avro format", ["schema-based"]),
    ("PROP.FORMAT.PARQUET", "FORMAT", "Parquet format", ["columnar"]),
    # SCOPE (10)
    ("PROP.SCOPE.LOCAL", "SCOPE", "Local scope", ["instance", "node"]),
    ("PROP.SCOPE.GLOBAL", "SCOPE", "Global scope", ["cluster", "world"]),
    ("PROP.SCOPE.REGIONAL", "SCOPE", "Regional scope", ["zone", "region"]),
    ("PROP.SCOPE.NAMESPACE", "SCOPE", "Namespace scope", ["tenant", "project"]),
    ("PROP.SCOPE.SESSION", "SCOPE", "Session scope", ["connection", "user"]),
    ("PROP.SCOPE.REQUEST", "SCOPE", "Request scope", ["call", "invocation"]),
    ("PROP.SCOPE.TRANSACTION", "SCOPE", "Transaction scope", ["atomic", "unit"]),
    ("PROP.SCOPE.THREAD", "SCOPE", "Thread scope", ["worker", "coroutine"]),
    ("PROP.SCOPE.PROCESS", "SCOPE", "Process scope", ["pid", "container"]),
    ("PROP.SCOPE.CLUSTER", "SCOPE", "Cluster scope", ["fleet", "swarm"]),
    # ENCODING (10)
    ("PROP.ENCODING.UTF8", "ENCODING", "UTF-8 encoding", ["unicode", "utf8"]),
    ("PROP.ENCODING.ASCII", "ENCODING", "ASCII encoding", ["7bit", "basic"]),
    ("PROP.ENCODING.BASE64", "ENCODING", "Base64 encoding", ["b64", "encoded"]),
    ("PROP.ENCODING.HEX", "ENCODING", "Hexadecimal encoding", ["hex", "base16"]),
    ("PROP.ENCODING.URL", "ENCODING", "URL encoding", ["percent", "urlencode"]),
    ("PROP.ENCODING.GZIP", "ENCODING", "Gzip compression", ["gz", "deflate"]),
    ("PROP.ENCODING.ZSTD", "ENCODING", "Zstandard compression", ["zstd"]),
    ("PROP.ENCODING.LZ4", "ENCODING", "LZ4 compression", ["fast compress"]),
    ("PROP.ENCODING.SNAPPY", "ENCODING", "Snappy compression", ["fast compress"]),
    ("PROP.ENCODING.BROTLI", "ENCODING", "Brotli compression", ["br"]),
    # SECURITY (10)
    ("PROP.SECURITY.ENCRYPTED", "SECURITY", "Encrypted data", ["protected", "secured"]),
    ("PROP.SECURITY.PLAINTEXT", "SECURITY", "Plaintext data", ["unencrypted", "clear"]),
    ("PROP.SECURITY.SIGNED", "SECURITY", "Digitally signed", ["authenticated"]),
    ("PROP.SECURITY.UNSIGNED", "SECURITY", "Not signed", ["unauthenticated"]),
    ("PROP.SECURITY.CLASSIFIED", "SECURITY", "Classified data", ["secret", "sensitive"]),
    ("PROP.SECURITY.PUBLIC", "SECURITY", "Public data", ["open", "unrestricted"]),
    ("PROP.SECURITY.INTERNAL", "SECURITY", "Internal only", ["private", "restricted"]),
    ("PROP.SECURITY.CONFIDENTIAL", "SECURITY", "Confidential data", ["private", "secret"]),
    ("PROP.SECURITY.COMPLIANT", "SECURITY", "Compliance verified", ["approved"]),
    ("PROP.SECURITY.NONCOMPLIANT", "SECURITY", "Not compliant", ["violation"]),
]

# REL (100 concepts)
REL = [
    # STRUCTURAL (20)
    ("REL.CONTAINS", "STRUCTURAL", "Contains relationship", ["includes", "has"]),
    ("REL.PART.OF", "STRUCTURAL", "Part of relationship", ["component", "member"]),
    ("REL.PARENT.OF", "STRUCTURAL", "Parent relationship", ["owner", "container"]),
    ("REL.CHILD.OF", "STRUCTURAL", "Child relationship", ["nested", "sub"]),
    ("REL.SIBLING.OF", "STRUCTURAL", "Sibling relationship", ["peer", "adjacent"]),
    ("REL.ROOT.OF", "STRUCTURAL", "Root element", ["top", "origin"]),
    ("REL.LEAF.OF", "STRUCTURAL", "Leaf element", ["terminal", "end"]),
    ("REL.ANCESTOR.OF", "STRUCTURAL", "Ancestor in hierarchy", ["grandparent"]),
    ("REL.DESCENDANT.OF", "STRUCTURAL", "Descendant in hierarchy", ["grandchild"]),
    ("REL.MEMBER.OF", "STRUCTURAL", "Member of group", ["belongs", "in"]),
    ("REL.GROUP.OF", "STRUCTURAL", "Group of items", ["collection", "set"]),
    ("REL.INSTANCE.OF", "STRUCTURAL", "Instance of type", ["example", "object"]),
    ("REL.TYPE.OF", "STRUCTURAL", "Type classification", ["class", "kind"]),
    ("REL.SUBTYPE.OF", "STRUCTURAL", "Subtype relationship", ["specialization"]),
    ("REL.SUPERTYPE.OF", "STRUCTURAL", "Supertype relationship", ["generalization"]),
    ("REL.IMPLEMENTS", "STRUCTURAL", "Implements interface", ["realizes"]),
    ("REL.EXTENDS", "STRUCTURAL", "Extends base", ["inherits", "derives"]),
    ("REL.COMPOSED.OF", "STRUCTURAL", "Composed of parts", ["built from"]),
    ("REL.WRAPS", "STRUCTURAL", "Wraps or decorates", ["decorates", "adapts"]),
    ("REL.PROXIES", "STRUCTURAL", "Proxies for", ["delegates", "represents"]),
    # ASSOCIATIVE (15)
    ("REL.RELATED.TO", "ASSOCIATIVE", "Related to", ["associated", "linked"]),
    ("REL.SIMILAR.TO", "ASSOCIATIVE", "Similar to", ["like", "resembles"]),
    ("REL.DIFFERENT.FROM", "ASSOCIATIVE", "Different from", ["unlike", "distinct"]),
    ("REL.EQUIVALENT.TO", "ASSOCIATIVE", "Equivalent to", ["equal", "same as"]),
    ("REL.OPPOSITE.OF", "ASSOCIATIVE", "Opposite of", ["inverse", "contrary"]),
    ("REL.ALIAS.OF", "ASSOCIATIVE", "Alias for", ["synonym", "alternate"]),
    ("REL.REFERENCE.TO", "ASSOCIATIVE", "Reference to", ["pointer", "link"]),
    ("REL.COPY.OF", "ASSOCIATIVE", "Copy of original", ["clone", "duplicate"]),
    ("REL.VERSION.OF", "ASSOCIATIVE", "Version of", ["revision", "iteration"]),
    ("REL.VARIANT.OF", "ASSOCIATIVE", "Variant of", ["alternative", "option"]),
    ("REL.COMPLEMENT.OF", "ASSOCIATIVE", "Complement of", ["supplement"]),
    ("REL.SUBSTITUTE.FOR", "ASSOCIATIVE", "Substitute for", ["replacement"]),
    ("REL.COMPATIBLE.WITH", "ASSOCIATIVE", "Compatible with", ["works with"]),
    ("REL.INCOMPATIBLE.WITH", "ASSOCIATIVE", "Incompatible with", ["conflicts"]),
    ("REL.MAPS.TO", "ASSOCIATIVE", "Maps to target", ["corresponds", "translates"]),
    # DEPENDENCY (15)
    ("REL.DEPENDS.ON", "DEPENDENCY", "Depends on", ["requires", "needs"]),
    ("REL.REQUIRED.BY", "DEPENDENCY", "Required by", ["needed by"]),
    ("REL.OPTIONAL.FOR", "DEPENDENCY", "Optional for", ["nice to have"]),
    ("REL.BLOCKS", "DEPENDENCY", "Blocks progress", ["prevents"]),
    ("REL.BLOCKED.BY", "DEPENDENCY", "Blocked by", ["waiting for"]),
    ("REL.ENABLES", "DEPENDENCY", "Enables capability", ["unlocks"]),
    ("REL.ENABLED.BY", "DEPENDENCY", "Enabled by", ["provided by"]),
    ("REL.IMPORTS", "DEPENDENCY", "Imports from", ["uses", "includes"]),
    ("REL.EXPORTS", "DEPENDENCY", "Exports to", ["provides", "shares"]),
    ("REL.CONSUMES", "DEPENDENCY", "Consumes resource", ["uses", "reads"]),
    ("REL.PRODUCES", "DEPENDENCY", "Produces output", ["creates", "writes"]),
    ("REL.PROVIDES", "DEPENDENCY", "Provides service", ["offers", "supplies"]),
    ("REL.USES", "DEPENDENCY", "Uses resource", ["utilizes"]),
    ("REL.USED.BY", "DEPENDENCY", "Used by consumer", ["consumed by"]),
    ("REL.UPGRADES", "DEPENDENCY", "Upgrades from", ["succeeds"]),
    # CAUSAL (15)
    ("REL.CAUSES", "CAUSAL", "Causes effect", ["triggers", "produces"]),
    ("REL.CAUSED.BY", "CAUSAL", "Caused by source", ["due to"]),
    ("REL.TRIGGERS", "CAUSAL", "Triggers event", ["initiates"]),
    ("REL.TRIGGERED.BY", "CAUSAL", "Triggered by event", ["initiated by"]),
    ("REL.PREVENTS", "CAUSAL", "Prevents outcome", ["avoids", "blocks"]),
    ("REL.MITIGATES", "CAUSAL", "Mitigates risk", ["reduces"]),
    ("REL.AMPLIFIES", "CAUSAL", "Amplifies effect", ["increases"]),
    ("REL.CORRELATES.WITH", "CAUSAL", "Correlates with", ["associated"]),
    ("REL.PRECEDES", "CAUSAL", "Precedes in sequence", ["comes before"]),
    ("REL.FOLLOWS", "CAUSAL", "Follows in sequence", ["comes after"]),
    ("REL.LEADS.TO", "CAUSAL", "Leads to outcome", ["results in"]),
    ("REL.RESULTS.FROM", "CAUSAL", "Results from cause", ["comes from"]),
    ("REL.INFLUENCES", "CAUSAL", "Influences behavior", ["affects"]),
    ("REL.INFLUENCED.BY", "CAUSAL", "Influenced by", ["affected by"]),
    ("REL.DETERMINES", "CAUSAL", "Determines outcome", ["decides"]),
    # TEMPORAL (10)
    ("REL.BEFORE", "TEMPORAL", "Before in time", ["prior", "earlier"]),
    ("REL.AFTER", "TEMPORAL", "After in time", ["later", "subsequent"]),
    ("REL.CONCURRENT.WITH", "TEMPORAL", "Concurrent with", ["simultaneous"]),
    ("REL.STARTS.WITH", "TEMPORAL", "Starts with event", ["begins at"]),
    ("REL.ENDS.WITH", "TEMPORAL", "Ends with event", ["finishes at"]),
    ("REL.OVERLAPS.WITH", "TEMPORAL", "Overlaps in time", ["intersects"]),
    ("REL.DURING", "TEMPORAL", "During period", ["within"]),
    ("REL.REPLACES", "TEMPORAL", "Replaces previous", ["supersedes"]),
    ("REL.REPLACED.BY", "TEMPORAL", "Replaced by newer", ["superseded"]),
    ("REL.EXPIRES.AT", "TEMPORAL", "Expires at time", ["until", "valid until"]),
    # OWNERSHIP (10)
    ("REL.OWNS", "OWNERSHIP", "Owns resource", ["possesses"]),
    ("REL.OWNED.BY", "OWNERSHIP", "Owned by entity", ["belongs to"]),
    ("REL.CREATED.BY", "OWNERSHIP", "Created by agent", ["authored by"]),
    ("REL.MANAGED.BY", "OWNERSHIP", "Managed by agent", ["administered by"]),
    ("REL.ASSIGNED.TO", "OWNERSHIP", "Assigned to agent", ["delegated to"]),
    ("REL.SHARED.WITH", "OWNERSHIP", "Shared with agent", ["accessible by"]),
    ("REL.RESTRICTED.TO", "OWNERSHIP", "Restricted to agent", ["limited to"]),
    ("REL.GRANTED.TO", "OWNERSHIP", "Granted to agent", ["permitted"]),
    ("REL.REVOKED.FROM", "OWNERSHIP", "Revoked from agent", ["removed"]),
    ("REL.DELEGATED.TO", "OWNERSHIP", "Delegated to agent", ["forwarded"]),
    # SPATIAL (15)
    ("REL.LOCATED.AT", "SPATIAL", "Located at place", ["positioned"]),
    ("REL.ADJACENT.TO", "SPATIAL", "Adjacent to", ["next to", "beside"]),
    ("REL.CONNECTED.TO", "SPATIAL", "Connected to", ["linked"]),
    ("REL.DISCONNECTED.FROM", "SPATIAL", "Disconnected from", ["separated"]),
    ("REL.UPSTREAM.OF", "SPATIAL", "Upstream in flow", ["before"]),
    ("REL.DOWNSTREAM.OF", "SPATIAL", "Downstream in flow", ["after"]),
    ("REL.INPUT.TO", "SPATIAL", "Input to process", ["feeds"]),
    ("REL.OUTPUT.OF", "SPATIAL", "Output of process", ["produces"]),
    ("REL.SOURCE.OF", "SPATIAL", "Source of data", ["origin"]),
    ("REL.TARGET.OF", "SPATIAL", "Target of action", ["destination"]),
    ("REL.ENDPOINT.OF", "SPATIAL", "Endpoint of", ["terminus"]),
    ("REL.GATEWAY.TO", "SPATIAL", "Gateway to resource", ["entry point"]),
    ("REL.BRIDGE.BETWEEN", "SPATIAL", "Bridge between", ["connector"]),
    ("REL.LAYER.OF", "SPATIAL", "Layer in stack", ["level", "tier"]),
    ("REL.CHANNEL.TO", "SPATIAL", "Communication channel", ["pipe", "conduit"]),
]

# LOG (50 concepts)
LOG = [
    # OPERATOR (15)
    ("LOG.AND", "OPERATOR", "Logical AND", ["all", "both"]),
    ("LOG.OR", "OPERATOR", "Logical OR", ["any", "either"]),
    ("LOG.NOT", "OPERATOR", "Logical NOT", ["negate", "inverse"]),
    ("LOG.XOR", "OPERATOR", "Exclusive OR", ["one of"]),
    ("LOG.NAND", "OPERATOR", "NOT AND", ["not all"]),
    ("LOG.NOR", "OPERATOR", "NOT OR", ["none"]),
    ("LOG.IMPLIES", "OPERATOR", "Logical implication", ["therefore"]),
    ("LOG.IFF", "OPERATOR", "If and only if", ["equivalent"]),
    ("LOG.EXISTS", "OPERATOR", "Existential quantifier", ["some", "there exists"]),
    ("LOG.FORALL", "OPERATOR", "Universal quantifier", ["all", "every"]),
    ("LOG.TRUE", "OPERATOR", "Boolean true", ["yes", "1"]),
    ("LOG.FALSE", "OPERATOR", "Boolean false", ["no", "0"]),
    ("LOG.NULL", "OPERATOR", "Null or undefined", ["none", "nil"]),
    ("LOG.EMPTY", "OPERATOR", "Empty value", ["blank", "void"]),
    ("LOG.UNKNOWN", "OPERATOR", "Unknown value", ["undefined", "indeterminate"]),
    # CONDITIONAL (10)
    ("LOG.IF", "CONDITIONAL", "If condition", ["when", "provided"]),
    ("LOG.THEN", "CONDITIONAL", "Then clause", ["result", "consequence"]),
    ("LOG.ELSE", "CONDITIONAL", "Else clause", ["otherwise", "alternative"]),
    ("LOG.SWITCH", "CONDITIONAL", "Switch statement", ["case", "match"]),
    ("LOG.CASE", "CONDITIONAL", "Case branch", ["option", "variant"]),
    ("LOG.DEFAULT", "CONDITIONAL", "Default case", ["fallback", "otherwise"]),
    ("LOG.WHILE", "CONDITIONAL", "While condition", ["loop", "repeat"]),
    ("LOG.UNTIL", "CONDITIONAL", "Until condition", ["stop when"]),
    ("LOG.WHEN", "CONDITIONAL", "When triggered", ["on event"]),
    ("LOG.UNLESS", "CONDITIONAL", "Unless condition", ["except when"]),
    # COMPARISON (15)
    ("LOG.EQUAL", "COMPARISON", "Equal to", ["eq", "same"]),
    ("LOG.NOT.EQUAL", "COMPARISON", "Not equal to", ["neq", "different"]),
    ("LOG.GREATER", "COMPARISON", "Greater than", ["gt", "more"]),
    ("LOG.LESS", "COMPARISON", "Less than", ["lt", "fewer"]),
    ("LOG.GREATER.EQUAL", "COMPARISON", "Greater or equal", ["gte", "at least"]),
    ("LOG.LESS.EQUAL", "COMPARISON", "Less or equal", ["lte", "at most"]),
    ("LOG.BETWEEN", "COMPARISON", "Between values", ["range", "within"]),
    ("LOG.IN", "COMPARISON", "Value in set", ["member of"]),
    ("LOG.NOT.IN", "COMPARISON", "Value not in set", ["not member"]),
    ("LOG.LIKE", "COMPARISON", "Pattern match", ["matches", "regex"]),
    ("LOG.NOT.LIKE", "COMPARISON", "No pattern match", ["not matches"]),
    ("LOG.CONTAINS", "COMPARISON", "Contains value", ["includes", "has"]),
    ("LOG.STARTS.WITH", "COMPARISON", "Starts with prefix", ["begins"]),
    ("LOG.ENDS.WITH", "COMPARISON", "Ends with suffix", ["terminates"]),
    ("LOG.IS.NULL", "COMPARISON", "Is null check", ["is none"]),
    # SET OPERATIONS (10)
    ("LOG.UNION", "SET", "Set union", ["combine", "merge"]),
    ("LOG.INTERSECT", "SET", "Set intersection", ["common", "overlap"]),
    ("LOG.DIFFERENCE", "SET", "Set difference", ["except", "minus"]),
    ("LOG.SUBSET", "SET", "Is subset", ["contained in"]),
    ("LOG.SUPERSET", "SET", "Is superset", ["contains all"]),
    ("LOG.DISJOINT", "SET", "Sets are disjoint", ["no overlap"]),
    ("LOG.COMPLEMENT", "SET", "Set complement", ["inverse"]),
    ("LOG.CARTESIAN", "SET", "Cartesian product", ["cross join"]),
    ("LOG.POWER.SET", "SET", "Power set", ["all subsets"]),
    ("LOG.PARTITION", "SET", "Partition set", ["divide", "group"]),
]

# MATH (100 concepts)
MATH = [
    # ARITHMETIC (15)
    ("MATH.ADD", "ARITHMETIC", "Addition", ["plus", "sum"]),
    ("MATH.SUBTRACT", "ARITHMETIC", "Subtraction", ["minus", "difference"]),
    ("MATH.MULTIPLY", "ARITHMETIC", "Multiplication", ["times", "product"]),
    ("MATH.DIVIDE", "ARITHMETIC", "Division", ["quotient", "ratio"]),
    ("MATH.MODULO", "ARITHMETIC", "Modulo operation", ["remainder", "mod"]),
    ("MATH.POWER", "ARITHMETIC", "Exponentiation", ["exponent", "raise"]),
    ("MATH.SQRT", "ARITHMETIC", "Square root", ["root"]),
    ("MATH.ABS", "ARITHMETIC", "Absolute value", ["magnitude"]),
    ("MATH.NEGATE", "ARITHMETIC", "Negation", ["opposite", "invert"]),
    ("MATH.INCREMENT", "ARITHMETIC", "Increment by one", ["add 1", "next"]),
    ("MATH.DECREMENT", "ARITHMETIC", "Decrement by one", ["subtract 1", "prev"]),
    ("MATH.FLOOR", "ARITHMETIC", "Floor function", ["round down"]),
    ("MATH.CEIL", "ARITHMETIC", "Ceiling function", ["round up"]),
    ("MATH.ROUND", "ARITHMETIC", "Round to nearest", ["approximate"]),
    ("MATH.TRUNCATE", "ARITHMETIC", "Truncate decimal", ["cut", "trim"]),
    # AGGREGATE (15)
    ("MATH.SUM", "AGGREGATE", "Sum total", ["total", "aggregate"]),
    ("MATH.AVERAGE", "AGGREGATE", "Average or mean", ["mean", "avg"]),
    ("MATH.MIN", "AGGREGATE", "Minimum value", ["lowest", "smallest"]),
    ("MATH.MAX", "AGGREGATE", "Maximum value", ["highest", "largest"]),
    ("MATH.COUNT", "AGGREGATE", "Count items", ["tally", "number"]),
    ("MATH.MEDIAN", "AGGREGATE", "Median value", ["middle", "50th"]),
    ("MATH.MODE", "AGGREGATE", "Mode value", ["most frequent"]),
    ("MATH.RANGE", "AGGREGATE", "Range of values", ["spread"]),
    ("MATH.VARIANCE", "AGGREGATE", "Variance", ["var", "spread"]),
    ("MATH.STDDEV", "AGGREGATE", "Standard deviation", ["sigma", "std"]),
    ("MATH.PERCENTILE", "AGGREGATE", "Percentile rank", ["quantile"]),
    ("MATH.HISTOGRAM", "AGGREGATE", "Histogram distribution", ["bins"]),
    ("MATH.CUMSUM", "AGGREGATE", "Cumulative sum", ["running total"]),
    ("MATH.MOVING.AVG", "AGGREGATE", "Moving average", ["rolling avg"]),
    ("MATH.WEIGHTED.AVG", "AGGREGATE", "Weighted average", ["weighted mean"]),
    # LINEAR ALGEBRA (15)
    ("MATH.MATRIX.MULTIPLY", "LINALG", "Matrix multiplication", ["matmul"]),
    ("MATH.MATRIX.TRANSPOSE", "LINALG", "Matrix transpose", ["swap axes"]),
    ("MATH.MATRIX.INVERSE", "LINALG", "Matrix inverse", ["invert"]),
    ("MATH.MATRIX.DETERMINANT", "LINALG", "Matrix determinant", ["det"]),
    ("MATH.DOT.PRODUCT", "LINALG", "Dot product", ["inner product"]),
    ("MATH.CROSS.PRODUCT", "LINALG", "Cross product", ["outer"]),
    ("MATH.NORM", "LINALG", "Vector norm", ["magnitude", "length"]),
    ("MATH.NORMALIZE", "LINALG", "Normalize vector", ["unit vector"]),
    ("MATH.EIGENVALUE", "LINALG", "Eigenvalue", ["lambda"]),
    ("MATH.SVD", "LINALG", "Singular value decomp", ["svd"]),
    ("MATH.PCA", "LINALG", "Principal components", ["pca"]),
    ("MATH.COSINE.SIMILARITY", "LINALG", "Cosine similarity", ["cos sim"]),
    ("MATH.EUCLIDEAN.DISTANCE", "LINALG", "Euclidean distance", ["l2"]),
    ("MATH.MANHATTAN.DISTANCE", "LINALG", "Manhattan distance", ["l1"]),
    ("MATH.HAMMING.DISTANCE", "LINALG", "Hamming distance", ["bitwise"]),
    # STATISTICS (15)
    ("MATH.STAT.MEAN", "STATISTICS", "Statistical mean", ["average"]),
    ("MATH.STAT.STDEV", "STATISTICS", "Std deviation", ["sigma"]),
    ("MATH.STAT.CORRELATION", "STATISTICS", "Correlation coeff", ["r value"]),
    ("MATH.STAT.REGRESSION", "STATISTICS", "Regression analysis", ["fit line"]),
    ("MATH.STAT.TTEST", "STATISTICS", "T-test", ["significance"]),
    ("MATH.STAT.ANOVA", "STATISTICS", "Analysis of variance", ["anova"]),
    ("MATH.STAT.CHI.SQUARE", "STATISTICS", "Chi-squared test", ["chi2"]),
    ("MATH.STAT.PVALUE", "STATISTICS", "P-value", ["significance"]),
    ("MATH.STAT.CONFIDENCE", "STATISTICS", "Confidence interval", ["ci"]),
    ("MATH.STAT.SAMPLE", "STATISTICS", "Random sample", ["subset"]),
    ("MATH.STAT.DISTRIBUTION", "STATISTICS", "Distribution type", ["pdf"]),
    ("MATH.STAT.NORMAL", "STATISTICS", "Normal distribution", ["gaussian"]),
    ("MATH.STAT.UNIFORM", "STATISTICS", "Uniform distribution", ["flat"]),
    ("MATH.STAT.POISSON", "STATISTICS", "Poisson distribution", ["events"]),
    ("MATH.STAT.BAYES", "STATISTICS", "Bayesian inference", ["posterior"]),
    # TRIGONOMETRY (10)
    ("MATH.SIN", "TRIGONOMETRY", "Sine function", ["sin"]),
    ("MATH.COS", "TRIGONOMETRY", "Cosine function", ["cos"]),
    ("MATH.TAN", "TRIGONOMETRY", "Tangent function", ["tan"]),
    ("MATH.ASIN", "TRIGONOMETRY", "Arc sine", ["inverse sin"]),
    ("MATH.ACOS", "TRIGONOMETRY", "Arc cosine", ["inverse cos"]),
    ("MATH.ATAN", "TRIGONOMETRY", "Arc tangent", ["inverse tan"]),
    ("MATH.ATAN2", "TRIGONOMETRY", "Two-argument atan", ["angle"]),
    ("MATH.DEGREES", "TRIGONOMETRY", "Convert to degrees", ["deg"]),
    ("MATH.RADIANS", "TRIGONOMETRY", "Convert to radians", ["rad"]),
    ("MATH.HYPOT", "TRIGONOMETRY", "Hypotenuse", ["distance"]),
    # OTHER (10)
    ("MATH.LOG", "FUNCTION", "Logarithm", ["ln", "log"]),
    ("MATH.LOG10", "FUNCTION", "Base-10 logarithm", ["common log"]),
    ("MATH.LOG2", "FUNCTION", "Base-2 logarithm", ["binary log"]),
    ("MATH.EXP", "FUNCTION", "Exponential function", ["e^x"]),
    ("MATH.FACTORIAL", "FUNCTION", "Factorial", ["n!"]),
    ("MATH.GCD", "FUNCTION", "Greatest common divisor", ["hcf"]),
    ("MATH.LCM", "FUNCTION", "Least common multiple", ["lcm"]),
    ("MATH.RANDOM", "FUNCTION", "Random number", ["rand"]),
    ("MATH.CLAMP", "FUNCTION", "Clamp to range", ["limit"]),
    ("MATH.INTERPOLATE", "FUNCTION", "Interpolation", ["lerp"]),
    # CONSTANTS (5)
    ("MATH.PI", "CONSTANT", "Pi constant", ["3.14159"]),
    ("MATH.E", "CONSTANT", "Euler's number", ["2.71828"]),
    ("MATH.INF", "CONSTANT", "Infinity", ["unlimited"]),
    ("MATH.NEG.INF", "CONSTANT", "Negative infinity", ["-inf"]),
    ("MATH.NAN", "CONSTANT", "Not a number", ["undefined"]),
]

# TIME (50 concepts)
TIME = [
    # RELATIVE (15)
    ("TIME.BEFORE", "RELATIVE", "Before in time", ["prior", "earlier"]),
    ("TIME.AFTER", "RELATIVE", "After in time", ["later", "subsequent"]),
    ("TIME.DURING", "RELATIVE", "During period", ["while", "throughout"]),
    ("TIME.PAST", "RELATIVE", "Past time", ["previous", "historical"]),
    ("TIME.FUTURE", "RELATIVE", "Future time", ["upcoming", "next"]),
    ("TIME.SINCE", "RELATIVE", "Since time point", ["from", "starting"]),
    ("TIME.UNTIL", "RELATIVE", "Until time point", ["to", "ending"]),
    ("TIME.AGO", "RELATIVE", "Time ago", ["back", "prior"]),
    ("TIME.FROM.NOW", "RELATIVE", "Time from now", ["ahead"]),
    ("TIME.RECENTLY", "RELATIVE", "Recently occurred", ["just", "lately"]),
    ("TIME.SOON", "RELATIVE", "Coming soon", ["shortly", "imminent"]),
    ("TIME.EARLIEST", "RELATIVE", "Earliest possible", ["first", "minimum"]),
    ("TIME.LATEST", "RELATIVE", "Latest possible", ["last", "deadline"]),
    ("TIME.NEXT", "RELATIVE", "Next occurrence", ["following"]),
    ("TIME.PREVIOUS", "RELATIVE", "Previous occurrence", ["preceding"]),
    # ABSOLUTE (10)
    ("TIME.NOW", "ABSOLUTE", "Current time", ["current", "present"]),
    ("TIME.TODAY", "ABSOLUTE", "Today's date", ["current day"]),
    ("TIME.YESTERDAY", "ABSOLUTE", "Yesterday", ["previous day"]),
    ("TIME.TOMORROW", "ABSOLUTE", "Tomorrow", ["next day"]),
    ("TIME.EPOCH", "ABSOLUTE", "Unix epoch", ["1970-01-01"]),
    ("TIME.START", "ABSOLUTE", "Start time", ["begin", "onset"]),
    ("TIME.END", "ABSOLUTE", "End time", ["finish", "conclusion"]),
    ("TIME.CREATED", "ABSOLUTE", "Creation time", ["born", "made"]),
    ("TIME.MODIFIED", "ABSOLUTE", "Modification time", ["updated", "changed"]),
    ("TIME.EXPIRED", "ABSOLUTE", "Expiration time", ["invalid after"]),
    # DURATION (15)
    ("TIME.DURATION", "DURATION", "Time duration", ["span", "length"]),
    ("TIME.MILLISECOND", "DURATION", "Milliseconds", ["ms"]),
    ("TIME.SECOND", "DURATION", "Seconds", ["sec", "s"]),
    ("TIME.MINUTE", "DURATION", "Minutes", ["min", "m"]),
    ("TIME.HOUR", "DURATION", "Hours", ["hr", "h"]),
    ("TIME.DAY", "DURATION", "Days", ["d"]),
    ("TIME.WEEK", "DURATION", "Weeks", ["wk"]),
    ("TIME.MONTH", "DURATION", "Months", ["mo"]),
    ("TIME.YEAR", "DURATION", "Years", ["yr"]),
    ("TIME.INSTANT", "DURATION", "Instantaneous", ["immediate"]),
    ("TIME.SHORT", "DURATION", "Short duration", ["brief"]),
    ("TIME.LONG", "DURATION", "Long duration", ["extended"]),
    ("TIME.INFINITE", "DURATION", "Infinite duration", ["forever"]),
    ("TIME.TTL", "DURATION", "Time to live", ["expiry", "lifetime"]),
    ("TIME.TIMEOUT", "DURATION", "Timeout period", ["deadline"]),
    # SCHEDULING (10)
    ("TIME.SCHEDULE.ONCE", "SCHEDULING", "Run once", ["one-time"]),
    ("TIME.SCHEDULE.RECURRING", "SCHEDULING", "Recurring schedule", ["repeated"]),
    ("TIME.SCHEDULE.CRON", "SCHEDULING", "Cron expression", ["periodic"]),
    ("TIME.SCHEDULE.INTERVAL", "SCHEDULING", "Fixed interval", ["every N"]),
    ("TIME.SCHEDULE.DELAY", "SCHEDULING", "Delayed execution", ["deferred"]),
    ("TIME.SCHEDULE.IMMEDIATE", "SCHEDULING", "Immediate execution", ["now"]),
    ("TIME.SCHEDULE.PEAK", "SCHEDULING", "Peak hours", ["busy time"]),
    ("TIME.SCHEDULE.OFFPEAK", "SCHEDULING", "Off-peak hours", ["quiet time"]),
    ("TIME.SCHEDULE.WINDOW", "SCHEDULING", "Time window", ["slot", "period"]),
    ("TIME.SCHEDULE.DEADLINE", "SCHEDULING", "Deadline time", ["due by"]),
]

# SPACE (50 concepts)
SPACE = [
    # CONTAINMENT (10)
    ("SPACE.INSIDE", "CONTAINMENT", "Inside or within", ["internal"]),
    ("SPACE.OUTSIDE", "CONTAINMENT", "Outside or external", ["external"]),
    ("SPACE.BOUNDARY", "CONTAINMENT", "At boundary", ["edge", "border"]),
    ("SPACE.CENTER", "CONTAINMENT", "At center", ["middle", "core"]),
    ("SPACE.SURFACE", "CONTAINMENT", "On surface", ["outer", "face"]),
    ("SPACE.INTERIOR", "CONTAINMENT", "In interior", ["inner", "deep"]),
    ("SPACE.ENCLOSED", "CONTAINMENT", "Enclosed space", ["contained"]),
    ("SPACE.OPEN", "CONTAINMENT", "Open space", ["exposed"]),
    ("SPACE.NESTED", "CONTAINMENT", "Nested level", ["inner", "recursive"]),
    ("SPACE.FLAT", "CONTAINMENT", "Flat structure", ["single level"]),
    # PROXIMITY (10)
    ("SPACE.NEAR", "PROXIMITY", "Near or close", ["adjacent"]),
    ("SPACE.FAR", "PROXIMITY", "Far or distant", ["remote"]),
    ("SPACE.LOCAL", "PROXIMITY", "Local scope", ["same node"]),
    ("SPACE.REMOTE", "PROXIMITY", "Remote location", ["different node"]),
    ("SPACE.ADJACENT", "PROXIMITY", "Directly adjacent", ["next to"]),
    ("SPACE.DISTRIBUTED", "PROXIMITY", "Distributed across", ["spread"]),
    ("SPACE.CENTRALIZED", "PROXIMITY", "Centralized in one", ["single point"]),
    ("SPACE.CLUSTERED", "PROXIMITY", "Clustered together", ["grouped"]),
    ("SPACE.SCATTERED", "PROXIMITY", "Scattered widely", ["dispersed"]),
    ("SPACE.COLOCATED", "PROXIMITY", "Co-located", ["same place"]),
    # DIRECTION (10)
    ("SPACE.ABOVE", "DIRECTION", "Above or over", ["top"]),
    ("SPACE.BELOW", "DIRECTION", "Below or under", ["bottom"]),
    ("SPACE.LEFT", "DIRECTION", "To the left", ["port"]),
    ("SPACE.RIGHT", "DIRECTION", "To the right", ["starboard"]),
    ("SPACE.FORWARD", "DIRECTION", "Forward direction", ["ahead"]),
    ("SPACE.BACKWARD", "DIRECTION", "Backward direction", ["behind"]),
    ("SPACE.INBOUND", "DIRECTION", "Inbound traffic", ["incoming"]),
    ("SPACE.OUTBOUND", "DIRECTION", "Outbound traffic", ["outgoing"]),
    ("SPACE.UPSTREAM", "DIRECTION", "Upstream in flow", ["source-ward"]),
    ("SPACE.DOWNSTREAM", "DIRECTION", "Downstream in flow", ["sink-ward"]),
    # TOPOLOGY (10)
    ("SPACE.TOPO.POINT", "TOPOLOGY", "Single point", ["node", "vertex"]),
    ("SPACE.TOPO.EDGE", "TOPOLOGY", "Edge or link", ["connection"]),
    ("SPACE.TOPO.PATH", "TOPOLOGY", "Path through graph", ["route"]),
    ("SPACE.TOPO.CYCLE", "TOPOLOGY", "Cycle in graph", ["loop"]),
    ("SPACE.TOPO.TREE", "TOPOLOGY", "Tree structure", ["hierarchy"]),
    ("SPACE.TOPO.MESH", "TOPOLOGY", "Mesh topology", ["fully connected"]),
    ("SPACE.TOPO.STAR", "TOPOLOGY", "Star topology", ["hub and spoke"]),
    ("SPACE.TOPO.RING", "TOPOLOGY", "Ring topology", ["circular"]),
    ("SPACE.TOPO.BUS", "TOPOLOGY", "Bus topology", ["linear"]),
    ("SPACE.TOPO.GRAPH", "TOPOLOGY", "Graph structure", ["network"]),
    # REGION (10)
    ("SPACE.REGION.ZONE", "REGION", "Availability zone", ["az"]),
    ("SPACE.REGION.DATACENTER", "REGION", "Data center", ["dc", "colo"]),
    ("SPACE.REGION.RACK", "REGION", "Server rack", ["cabinet"]),
    ("SPACE.REGION.NODE", "REGION", "Single node", ["host", "server"]),
    ("SPACE.REGION.POD", "REGION", "Pod or group", ["cell"]),
    ("SPACE.REGION.PARTITION", "REGION", "Partition or shard", ["segment"]),
    ("SPACE.REGION.REPLICA", "REGION", "Replica location", ["copy"]),
    ("SPACE.REGION.PRIMARY", "REGION", "Primary location", ["master"]),
    ("SPACE.REGION.SECONDARY", "REGION", "Secondary location", ["slave"]),
    ("SPACE.REGION.EDGE", "REGION", "Edge location", ["cdn", "pop"]),
]

# DATA (100 concepts)
DATA = [
    # STRUCTURE (20)
    ("DATA.LIST", "STRUCTURE", "List or array", ["array", "sequence"]),
    ("DATA.DICT", "STRUCTURE", "Dictionary or map", ["map", "object"]),
    ("DATA.SET", "STRUCTURE", "Set collection", ["unique"]),
    ("DATA.TUPLE", "STRUCTURE", "Tuple or pair", ["fixed sequence"]),
    ("DATA.STRING", "STRUCTURE", "String type", ["text", "char"]),
    ("DATA.INTEGER", "STRUCTURE", "Integer type", ["int", "whole"]),
    ("DATA.FLOAT", "STRUCTURE", "Float type", ["decimal", "real"]),
    ("DATA.QUEUE", "STRUCTURE", "FIFO queue", ["fifo"]),
    ("DATA.STACK", "STRUCTURE", "LIFO stack", ["lifo"]),
    ("DATA.DEQUE", "STRUCTURE", "Double-ended queue", ["deque"]),
    ("DATA.HEAP", "STRUCTURE", "Heap or priority queue", ["priority queue"]),
    ("DATA.TREE", "STRUCTURE", "Tree structure", ["hierarchical"]),
    ("DATA.GRAPH", "STRUCTURE", "Graph structure", ["network"]),
    ("DATA.LINKED.LIST", "STRUCTURE", "Linked list", ["chain"]),
    ("DATA.HASH.TABLE", "STRUCTURE", "Hash table", ["hashtable", "map"]),
    ("DATA.BTREE", "STRUCTURE", "B-tree index", ["balanced tree"]),
    ("DATA.TRIE", "STRUCTURE", "Trie or prefix tree", ["autocomplete"]),
    ("DATA.BLOOM.FILTER", "STRUCTURE", "Bloom filter", ["probabilistic set"]),
    ("DATA.RING.BUFFER", "STRUCTURE", "Ring buffer", ["circular buffer"]),
    ("DATA.SPARSE.ARRAY", "STRUCTURE", "Sparse array", ["compressed"]),
    # PRIMITIVE (15)
    ("DATA.BOOLEAN", "PRIMITIVE", "Boolean type", ["bool", "flag"]),
    ("DATA.BYTE", "PRIMITIVE", "Byte value", ["uint8", "octet"]),
    ("DATA.INT8", "PRIMITIVE", "8-bit integer", ["sbyte"]),
    ("DATA.INT16", "PRIMITIVE", "16-bit integer", ["short"]),
    ("DATA.INT32", "PRIMITIVE", "32-bit integer", ["int"]),
    ("DATA.INT64", "PRIMITIVE", "64-bit integer", ["long"]),
    ("DATA.UINT32", "PRIMITIVE", "Unsigned 32-bit", ["uint"]),
    ("DATA.UINT64", "PRIMITIVE", "Unsigned 64-bit", ["ulong"]),
    ("DATA.FLOAT32", "PRIMITIVE", "32-bit float", ["single"]),
    ("DATA.FLOAT64", "PRIMITIVE", "64-bit float", ["double"]),
    ("DATA.DECIMAL", "PRIMITIVE", "Decimal precision", ["exact"]),
    ("DATA.CHAR", "PRIMITIVE", "Single character", ["rune"]),
    ("DATA.NULL", "PRIMITIVE", "Null value", ["none", "nil"]),
    ("DATA.VOID", "PRIMITIVE", "Void type", ["nothing"]),
    ("DATA.ENUM", "PRIMITIVE", "Enumeration type", ["choices"]),
    # COMPLEX (15)
    ("DATA.TIMESTAMP", "COMPLEX", "Timestamp value", ["datetime"]),
    ("DATA.DATE", "COMPLEX", "Date value", ["calendar date"]),
    ("DATA.TIME", "COMPLEX", "Time value", ["clock time"]),
    ("DATA.DURATION", "COMPLEX", "Duration value", ["interval"]),
    ("DATA.UUID", "COMPLEX", "UUID identifier", ["guid", "unique id"]),
    ("DATA.URI", "COMPLEX", "URI or URL", ["link", "address"]),
    ("DATA.EMAIL", "COMPLEX", "Email address", ["mail"]),
    ("DATA.IP.ADDRESS", "COMPLEX", "IP address", ["ipv4", "ipv6"]),
    ("DATA.MAC.ADDRESS", "COMPLEX", "MAC address", ["hardware addr"]),
    ("DATA.REGEX", "COMPLEX", "Regular expression", ["pattern"]),
    ("DATA.SEMVER", "COMPLEX", "Semantic version", ["version"]),
    ("DATA.CURRENCY", "COMPLEX", "Currency value", ["money"]),
    ("DATA.GEO.POINT", "COMPLEX", "Geographic point", ["lat/long"]),
    ("DATA.RANGE", "COMPLEX", "Range of values", ["interval"]),
    ("DATA.OPTIONAL", "COMPLEX", "Optional value", ["maybe", "nullable"]),
    # SERIALIZATION (10)
    ("DATA.JSON.OBJECT", "SERIALIZATION", "JSON object", ["dict"]),
    ("DATA.JSON.ARRAY", "SERIALIZATION", "JSON array", ["list"]),
    ("DATA.JSON.PATCH", "SERIALIZATION", "JSON Patch", ["rfc6902"]),
    ("DATA.JSON.POINTER", "SERIALIZATION", "JSON Pointer", ["path"]),
    ("DATA.JSON.SCHEMA", "SERIALIZATION", "JSON Schema", ["validation"]),
    ("DATA.PROTOBUF.MSG", "SERIALIZATION", "Protobuf message", ["proto"]),
    ("DATA.AVRO.RECORD", "SERIALIZATION", "Avro record", ["schema"]),
    ("DATA.MSGPACK.OBJ", "SERIALIZATION", "MessagePack object", ["binary"]),
    ("DATA.CBOR.OBJ", "SERIALIZATION", "CBOR object", ["binary"]),
    ("DATA.XML.ELEMENT", "SERIALIZATION", "XML element", ["node"]),
    # COLLECTION (10)
    ("DATA.BATCH", "COLLECTION", "Batch of items", ["group"]),
    ("DATA.PAGE", "COLLECTION", "Page of results", ["slice"]),
    ("DATA.CHUNK", "COLLECTION", "Data chunk", ["segment"]),
    ("DATA.PARTITION", "COLLECTION", "Data partition", ["shard"]),
    ("DATA.WINDOW", "COLLECTION", "Sliding window", ["frame"]),
    ("DATA.STREAM", "COLLECTION", "Data stream", ["flow"]),
    ("DATA.CURSOR", "COLLECTION", "Database cursor", ["iterator"]),
    ("DATA.ITERATOR", "COLLECTION", "Iterator object", ["generator"]),
    ("DATA.BUFFER", "COLLECTION", "Data buffer", ["pool"]),
    ("DATA.PIPELINE", "COLLECTION", "Data pipeline", ["chain"]),
    # SCHEMA (10)
    ("DATA.SCHEMA.TABLE", "SCHEMA", "Table schema", ["relation"]),
    ("DATA.SCHEMA.COLUMN", "SCHEMA", "Column definition", ["field"]),
    ("DATA.SCHEMA.INDEX", "SCHEMA", "Index definition", ["key"]),
    ("DATA.SCHEMA.CONSTRAINT", "SCHEMA", "Constraint rule", ["check"]),
    ("DATA.SCHEMA.FOREIGN.KEY", "SCHEMA", "Foreign key", ["reference"]),
    ("DATA.SCHEMA.PRIMARY.KEY", "SCHEMA", "Primary key", ["id"]),
    ("DATA.SCHEMA.VIEW", "SCHEMA", "View definition", ["projection"]),
    ("DATA.SCHEMA.MIGRATION", "SCHEMA", "Schema migration", ["evolution"]),
    ("DATA.SCHEMA.TRIGGER", "SCHEMA", "Database trigger", ["hook"]),
    ("DATA.SCHEMA.PROCEDURE", "SCHEMA", "Stored procedure", ["function"]),
    # ENCODING (10)
    ("DATA.ENCODING.UTF8", "ENCODING", "UTF-8 encoded", ["unicode"]),
    ("DATA.ENCODING.ASCII", "ENCODING", "ASCII encoded", ["7-bit"]),
    ("DATA.ENCODING.BASE64", "ENCODING", "Base64 encoded", ["b64"]),
    ("DATA.ENCODING.HEX", "ENCODING", "Hex encoded", ["base16"]),
    ("DATA.ENCODING.URL", "ENCODING", "URL encoded", ["percent"]),
    ("DATA.ENCODING.HTML", "ENCODING", "HTML entities", ["escaped"]),
    ("DATA.ENCODING.BINARY", "ENCODING", "Raw binary", ["bytes"]),
    ("DATA.ENCODING.COMPRESSED", "ENCODING", "Compressed data", ["zipped"]),
    ("DATA.ENCODING.ENCRYPTED", "ENCODING", "Encrypted data", ["ciphered"]),
    ("DATA.ENCODING.SIGNED", "ENCODING", "Signed data", ["verified"]),
    # ACCESS (10)
    ("DATA.ACCESS.READ", "ACCESS", "Read access", ["get", "fetch"]),
    ("DATA.ACCESS.WRITE", "ACCESS", "Write access", ["put", "set"]),
    ("DATA.ACCESS.APPEND", "ACCESS", "Append access", ["add", "push"]),
    ("DATA.ACCESS.DELETE", "ACCESS", "Delete access", ["remove"]),
    ("DATA.ACCESS.EXECUTE", "ACCESS", "Execute access", ["run"]),
    ("DATA.ACCESS.ADMIN", "ACCESS", "Admin access", ["full"]),
    ("DATA.ACCESS.OWNER", "ACCESS", "Owner access", ["creator"]),
    ("DATA.ACCESS.SHARED", "ACCESS", "Shared access", ["collaborative"]),
    ("DATA.ACCESS.READONLY", "ACCESS", "Read-only access", ["immutable"]),
    ("DATA.ACCESS.WRITEONLY", "ACCESS", "Write-only access", ["sink"]),
]

# META (100 concepts)
META = [
    # STATUS (15)
    ("META.STATUS.SUCCESS", "STATUS", "Operation successful", ["ok", "done"]),
    ("META.STATUS.FAILURE", "STATUS", "Operation failed", ["error", "failed"]),
    ("META.STATUS.PENDING", "STATUS", "Operation pending", ["waiting"]),
    ("META.STATUS.RUNNING", "STATUS", "Operation running", ["in progress"]),
    ("META.STATUS.CANCELLED", "STATUS", "Operation cancelled", ["aborted"]),
    ("META.STATUS.TIMEOUT", "STATUS", "Operation timed out", ["expired"]),
    ("META.STATUS.PARTIAL", "STATUS", "Partial completion", ["incomplete"]),
    ("META.STATUS.SKIPPED", "STATUS", "Operation skipped", ["bypassed"]),
    ("META.STATUS.QUEUED", "STATUS", "Queued for execution", ["scheduled"]),
    ("META.STATUS.RETRY", "STATUS", "Retrying operation", ["reattempting"]),
    ("META.STATUS.BLOCKED", "STATUS", "Operation blocked", ["stuck"]),
    ("META.STATUS.DEGRADED", "STATUS", "Degraded operation", ["impaired"]),
    ("META.STATUS.UNKNOWN", "STATUS", "Unknown status", ["indeterminate"]),
    ("META.STATUS.CREATED", "STATUS", "Resource created", ["new"]),
    ("META.STATUS.DELETED", "STATUS", "Resource deleted", ["removed"]),
    # ERROR (20)
    ("META.ERROR.VALIDATION", "ERROR", "Validation error", ["invalid"]),
    ("META.ERROR.TIMEOUT", "ERROR", "Timeout error", ["expired"]),
    ("META.ERROR.NOT_FOUND", "ERROR", "Resource not found", ["missing"]),
    ("META.ERROR.PERMISSION", "ERROR", "Permission denied", ["forbidden"]),
    ("META.ERROR.NETWORK", "ERROR", "Network error", ["connection"]),
    ("META.ERROR.GENERAL", "ERROR", "General error", ["unknown"]),
    ("META.ERROR.INTERNAL", "ERROR", "Internal server error", ["bug"]),
    ("META.ERROR.CONFLICT", "ERROR", "Resource conflict", ["duplicate"]),
    ("META.ERROR.RATE_LIMIT", "ERROR", "Rate limit exceeded", ["throttled"]),
    ("META.ERROR.QUOTA", "ERROR", "Quota exceeded", ["limit"]),
    ("META.ERROR.UNAVAILABLE", "ERROR", "Service unavailable", ["down"]),
    ("META.ERROR.DEPRECATED", "ERROR", "Deprecated feature", ["obsolete"]),
    ("META.ERROR.UNSUPPORTED", "ERROR", "Unsupported operation", ["not implemented"]),
    ("META.ERROR.OVERFLOW", "ERROR", "Overflow error", ["too large"]),
    ("META.ERROR.UNDERFLOW", "ERROR", "Underflow error", ["too small"]),
    ("META.ERROR.ENCODING", "ERROR", "Encoding error", ["codec"]),
    ("META.ERROR.DECODING", "ERROR", "Decoding error", ["parse"]),
    ("META.ERROR.SIGNATURE", "ERROR", "Signature error", ["tampered"]),
    ("META.ERROR.REPLAY", "ERROR", "Replay attack detected", ["duplicate"]),
    ("META.ERROR.SCHEMA", "ERROR", "Schema mismatch", ["incompatible"]),
    # CONTROL (15)
    ("META.RESPONSE", "CONTROL", "Response to request", ["reply"]),
    ("META.REQUEST", "CONTROL", "Request for action", ["ask"]),
    ("META.ACK", "CONTROL", "Acknowledgement", ["received"]),
    ("META.NACK", "CONTROL", "Negative ack", ["rejected"]),
    ("META.HEARTBEAT", "CONTROL", "Heartbeat signal", ["alive"]),
    ("META.HANDSHAKE", "CONTROL", "Protocol handshake", ["init"]),
    ("META.GOODBYE", "CONTROL", "Disconnect signal", ["bye"]),
    ("META.RESET", "CONTROL", "Reset connection", ["clear"]),
    ("META.REDIRECT", "CONTROL", "Redirect to other", ["forward"]),
    ("META.RETRY", "CONTROL", "Retry request", ["again"]),
    ("META.CANCEL", "CONTROL", "Cancel operation", ["abort"]),
    ("META.KEEPALIVE", "CONTROL", "Keep alive signal", ["ping"]),
    ("META.FLOW.CONTROL", "CONTROL", "Flow control", ["backpressure"]),
    ("META.RATE.LIMIT", "CONTROL", "Rate limiting", ["throttle"]),
    ("META.CIRCUIT.BREAK", "CONTROL", "Circuit breaker", ["protection"]),
    # PROTOCOL (15)
    ("META.PROTOCOL.VERSION", "PROTOCOL", "Protocol version", ["ver"]),
    ("META.PROTOCOL.PULSE", "PROTOCOL", "PULSE protocol", ["pulse"]),
    ("META.PROTOCOL.HTTP", "PROTOCOL", "HTTP protocol", ["web"]),
    ("META.PROTOCOL.HTTPS", "PROTOCOL", "HTTPS protocol", ["secure web"]),
    ("META.PROTOCOL.WS", "PROTOCOL", "WebSocket", ["ws"]),
    ("META.PROTOCOL.WSS", "PROTOCOL", "Secure WebSocket", ["wss"]),
    ("META.PROTOCOL.GRPC", "PROTOCOL", "gRPC protocol", ["rpc"]),
    ("META.PROTOCOL.MQTT", "PROTOCOL", "MQTT protocol", ["iot"]),
    ("META.PROTOCOL.AMQP", "PROTOCOL", "AMQP protocol", ["messaging"]),
    ("META.PROTOCOL.TCP", "PROTOCOL", "TCP protocol", ["stream"]),
    ("META.PROTOCOL.UDP", "PROTOCOL", "UDP protocol", ["datagram"]),
    ("META.PROTOCOL.TLS", "PROTOCOL", "TLS protocol", ["ssl"]),
    ("META.PROTOCOL.QUIC", "PROTOCOL", "QUIC protocol", ["http3"]),
    ("META.PROTOCOL.DNS", "PROTOCOL", "DNS protocol", ["resolution"]),
    ("META.PROTOCOL.SSH", "PROTOCOL", "SSH protocol", ["secure shell"]),
    # CAPABILITY (10)
    ("META.CAP.ENCODE.JSON", "CAPABILITY", "JSON encoding", ["json"]),
    ("META.CAP.ENCODE.BINARY", "CAPABILITY", "Binary encoding", ["msgpack"]),
    ("META.CAP.ENCODE.COMPACT", "CAPABILITY", "Compact encoding", ["pulse compact"]),
    ("META.CAP.SECURITY.SIGN", "CAPABILITY", "Message signing", ["hmac"]),
    ("META.CAP.SECURITY.ENCRYPT", "CAPABILITY", "Encryption support", ["tls"]),
    ("META.CAP.STREAM", "CAPABILITY", "Streaming support", ["chunked"]),
    ("META.CAP.BATCH", "CAPABILITY", "Batch operations", ["bulk"]),
    ("META.CAP.SUBSCRIBE", "CAPABILITY", "Pub/sub support", ["events"]),
    ("META.CAP.COMPRESS", "CAPABILITY", "Compression support", ["gzip"]),
    ("META.CAP.CACHE", "CAPABILITY", "Caching support", ["etag"]),
    # AUDIT (10)
    ("META.AUDIT.CREATE", "AUDIT", "Resource created", ["born"]),
    ("META.AUDIT.READ", "AUDIT", "Resource read", ["accessed"]),
    ("META.AUDIT.UPDATE", "AUDIT", "Resource updated", ["modified"]),
    ("META.AUDIT.DELETE", "AUDIT", "Resource deleted", ["removed"]),
    ("META.AUDIT.LOGIN", "AUDIT", "Login event", ["authenticated"]),
    ("META.AUDIT.LOGOUT", "AUDIT", "Logout event", ["disconnected"]),
    ("META.AUDIT.PERMISSION.CHANGE", "AUDIT", "Permission changed", ["acl"]),
    ("META.AUDIT.CONFIG.CHANGE", "AUDIT", "Config changed", ["settings"]),
    ("META.AUDIT.SECURITY.EVENT", "AUDIT", "Security event", ["incident"]),
    ("META.AUDIT.COMPLIANCE", "AUDIT", "Compliance event", ["regulation"]),
    # INFO (15)
    ("META.INFO.AGENT", "INFO", "Agent information", ["about"]),
    ("META.INFO.PROTOCOL", "INFO", "Protocol information", ["spec"]),
    ("META.INFO.CAPABILITY", "INFO", "Capability listing", ["features"]),
    ("META.INFO.VOCABULARY", "INFO", "Vocabulary info", ["concepts"]),
    ("META.INFO.SCHEMA", "INFO", "Schema information", ["structure"]),
    ("META.INFO.HEALTH", "INFO", "Health information", ["status"]),
    ("META.INFO.METRICS", "INFO", "Metrics information", ["stats"]),
    ("META.INFO.VERSION", "INFO", "Version information", ["build"]),
    ("META.INFO.UPTIME", "INFO", "Uptime information", ["duration"]),
    ("META.INFO.LOAD", "INFO", "Load information", ["utilization"]),
    ("META.INFO.CONNECTIONS", "INFO", "Connection info", ["peers"]),
    ("META.INFO.ROUTES", "INFO", "Routing information", ["endpoints"]),
    ("META.INFO.CONFIG", "INFO", "Configuration info", ["settings"]),
    ("META.INFO.LIMITS", "INFO", "Rate/size limits", ["quotas"]),
    ("META.INFO.DOCUMENTATION", "INFO", "Documentation link", ["docs"]),
]

print(f"PROP: {len(PROP)}")
print(f"REL: {len(REL)}")
print(f"LOG: {len(LOG)}")
print(f"MATH: {len(MATH)}")
print(f"TIME: {len(TIME)}")
print(f"SPACE: {len(SPACE)}")
print(f"DATA: {len(DATA)}")
print(f"META: {len(META)}")
total = len(PROP) + len(REL) + len(LOG) + len(MATH) + len(TIME) + len(SPACE) + len(DATA) + len(META)
print(f"Remaining total: {total}")
