"""Generate vocabulary.py with 1000 concepts."""

# Each entry: (concept_id, subcategory, description, examples_list)
# Format: CATEGORY.SUBCATEGORY.SPECIFIC

CONCEPTS = []

# ===== ENT (100 concepts) =====
ENT = [
    # DATA (20)
    ("ENT.DATA.TEXT", "DATA", "Text data or document", ["string", "document", "article"]),
    ("ENT.DATA.IMAGE", "DATA", "Image data", ["picture", "photo", "graphic"]),
    ("ENT.DATA.VIDEO", "DATA", "Video data", ["movie", "clip", "recording"]),
    ("ENT.DATA.AUDIO", "DATA", "Audio data", ["sound", "music", "speech"]),
    ("ENT.DATA.NUMBER", "DATA", "Numeric data", ["integer", "float", "decimal"]),
    ("ENT.DATA.BOOLEAN", "DATA", "Boolean value", ["true", "false", "flag"]),
    ("ENT.DATA.JSON", "DATA", "JSON formatted data", ["object", "structure"]),
    ("ENT.DATA.XML", "DATA", "XML formatted data", ["markup", "structure"]),
    ("ENT.DATA.CSV", "DATA", "CSV formatted data", ["spreadsheet", "table"]),
    ("ENT.DATA.BINARY", "DATA", "Binary data", ["bytes", "blob", "raw"]),
    ("ENT.DATA.HTML", "DATA", "HTML content", ["webpage", "markup"]),
    ("ENT.DATA.MARKDOWN", "DATA", "Markdown text", ["formatted", "rich text"]),
    ("ENT.DATA.YAML", "DATA", "YAML configuration", ["config", "settings"]),
    ("ENT.DATA.PROTOBUF", "DATA", "Protocol buffer data", ["proto", "serialized"]),
    ("ENT.DATA.GRAPH", "DATA", "Graph or network data", ["nodes", "edges"]),
    ("ENT.DATA.TABLE", "DATA", "Tabular data", ["rows", "columns", "grid"]),
    ("ENT.DATA.VECTOR", "DATA", "Vector embedding data", ["embedding", "feature"]),
    ("ENT.DATA.MATRIX", "DATA", "Matrix data", ["2d array", "grid"]),
    ("ENT.DATA.TENSOR", "DATA", "Tensor data", ["multidimensional", "nd-array"]),
    ("ENT.DATA.LOG", "DATA", "Log data", ["entries", "records", "trace"]),
    # AGENT (15)
    ("ENT.AGENT.AI", "AGENT", "Artificial intelligence agent", ["bot", "assistant", "model"]),
    ("ENT.AGENT.HUMAN", "AGENT", "Human user or operator", ["user", "person", "operator"]),
    ("ENT.AGENT.SERVICE", "AGENT", "Service or microservice", ["api", "endpoint"]),
    ("ENT.AGENT.SYSTEM", "AGENT", "System or platform", ["platform", "infrastructure"]),
    ("ENT.AGENT.BOT", "AGENT", "Automated bot agent", ["robot", "crawler", "scraper"]),
    ("ENT.AGENT.ORCHESTRATOR", "AGENT", "Orchestration agent", ["coordinator", "conductor"]),
    ("ENT.AGENT.MONITOR", "AGENT", "Monitoring agent", ["watcher", "observer"]),
    ("ENT.AGENT.PROXY", "AGENT", "Proxy or intermediary", ["middleware", "relay"]),
    ("ENT.AGENT.GATEWAY", "AGENT", "Gateway or entry point", ["ingress", "entry"]),
    ("ENT.AGENT.SCHEDULER", "AGENT", "Scheduling agent", ["cron", "timer"]),
    ("ENT.AGENT.WORKER", "AGENT", "Worker process agent", ["executor", "runner"]),
    ("ENT.AGENT.PIPELINE", "AGENT", "Pipeline processor", ["chain", "workflow"]),
    ("ENT.AGENT.ROUTER", "AGENT", "Message router", ["dispatcher", "switch"]),
    ("ENT.AGENT.VALIDATOR", "AGENT", "Validation agent", ["checker", "verifier"]),
    ("ENT.AGENT.TRANSFORMER", "AGENT", "Data transformation agent", ["converter", "mapper"]),
    # RESOURCE (20)
    ("ENT.RESOURCE.DATABASE", "RESOURCE", "Database system", ["db", "storage"]),
    ("ENT.RESOURCE.FILE", "RESOURCE", "File system resource", ["document", "file"]),
    ("ENT.RESOURCE.API", "RESOURCE", "API endpoint", ["endpoint", "interface"]),
    ("ENT.RESOURCE.NETWORK", "RESOURCE", "Network resource", ["connection", "socket"]),
    ("ENT.RESOURCE.MEMORY", "RESOURCE", "Memory or cache", ["ram", "cache", "buffer"]),
    ("ENT.RESOURCE.QUEUE", "RESOURCE", "Message queue", ["queue", "buffer"]),
    ("ENT.RESOURCE.STORAGE", "RESOURCE", "Storage system", ["disk", "volume"]),
    ("ENT.RESOURCE.COMPUTE", "RESOURCE", "Compute resource", ["cpu", "processing"]),
    ("ENT.RESOURCE.GPU", "RESOURCE", "GPU resource", ["graphics", "cuda"]),
    ("ENT.RESOURCE.CONTAINER", "RESOURCE", "Container or sandbox", ["docker", "pod"]),
    ("ENT.RESOURCE.CLUSTER", "RESOURCE", "Compute cluster", ["swarm", "fleet"]),
    ("ENT.RESOURCE.REGISTRY", "RESOURCE", "Service registry", ["catalog", "directory"]),
    ("ENT.RESOURCE.BROKER", "RESOURCE", "Message broker", ["kafka", "rabbitmq"]),
    ("ENT.RESOURCE.CACHE", "RESOURCE", "Cache system", ["redis", "memcached"]),
    ("ENT.RESOURCE.CDN", "RESOURCE", "Content delivery network", ["edge", "distribution"]),
    ("ENT.RESOURCE.DNS", "RESOURCE", "Domain name service", ["resolver", "nameserver"]),
    ("ENT.RESOURCE.LOADBALANCER", "RESOURCE", "Load balancer", ["lb", "distributor"]),
    ("ENT.RESOURCE.FIREWALL", "RESOURCE", "Firewall or WAF", ["filter", "shield"]),
    ("ENT.RESOURCE.VAULT", "RESOURCE", "Secret vault", ["secrets", "keystore"]),
    ("ENT.RESOURCE.LOGGER", "RESOURCE", "Logging service", ["log collector", "sink"]),
    # OBJECT (20)
    ("ENT.OBJECT.MODEL", "OBJECT", "ML model or data model", ["neural net", "schema"]),
    ("ENT.OBJECT.SCHEMA", "OBJECT", "Data schema definition", ["structure", "blueprint"]),
    ("ENT.OBJECT.CONFIG", "OBJECT", "Configuration object", ["settings", "preferences"]),
    ("ENT.OBJECT.TOKEN", "OBJECT", "Authentication token", ["jwt", "session token"]),
    ("ENT.OBJECT.SESSION", "OBJECT", "User or agent session", ["context", "connection"]),
    ("ENT.OBJECT.CREDENTIAL", "OBJECT", "Authentication credential", ["login", "password"]),
    ("ENT.OBJECT.CERTIFICATE", "OBJECT", "Security certificate", ["ssl", "x509"]),
    ("ENT.OBJECT.KEY", "OBJECT", "Cryptographic key", ["secret", "public key"]),
    ("ENT.OBJECT.EVENT", "OBJECT", "System event", ["notification", "signal"]),
    ("ENT.OBJECT.TASK", "OBJECT", "Task or work item", ["job", "unit of work"]),
    ("ENT.OBJECT.WORKFLOW", "OBJECT", "Workflow definition", ["process", "pipeline"]),
    ("ENT.OBJECT.RULE", "OBJECT", "Business rule", ["policy", "constraint"]),
    ("ENT.OBJECT.POLICY", "OBJECT", "Security or access policy", ["acl", "permission"]),
    ("ENT.OBJECT.TEMPLATE", "OBJECT", "Template or pattern", ["blueprint", "boilerplate"]),
    ("ENT.OBJECT.METRIC", "OBJECT", "Performance metric", ["measurement", "kpi"]),
    ("ENT.OBJECT.ALERT", "OBJECT", "Alert or alarm", ["warning", "notification"]),
    ("ENT.OBJECT.REPORT", "OBJECT", "Report or summary", ["analysis", "document"]),
    ("ENT.OBJECT.MESSAGE", "OBJECT", "Message or communication", ["packet", "payload"]),
    ("ENT.OBJECT.TRANSACTION", "OBJECT", "Transaction unit", ["operation", "atomic"]),
    ("ENT.OBJECT.SNAPSHOT", "OBJECT", "State snapshot", ["checkpoint", "backup"]),
    # DOMAIN (15)
    ("ENT.DOMAIN.WEB", "DOMAIN", "Web domain", ["http", "website"]),
    ("ENT.DOMAIN.MOBILE", "DOMAIN", "Mobile platform", ["ios", "android"]),
    ("ENT.DOMAIN.CLOUD", "DOMAIN", "Cloud platform", ["aws", "azure", "gcp"]),
    ("ENT.DOMAIN.IOT", "DOMAIN", "Internet of Things", ["sensor", "device"]),
    ("ENT.DOMAIN.EDGE", "DOMAIN", "Edge computing", ["local", "proximity"]),
    ("ENT.DOMAIN.BLOCKCHAIN", "DOMAIN", "Blockchain network", ["distributed ledger"]),
    ("ENT.DOMAIN.ML", "DOMAIN", "Machine learning", ["ai", "deep learning"]),
    ("ENT.DOMAIN.NLP", "DOMAIN", "Natural language processing", ["text analysis"]),
    ("ENT.DOMAIN.CV", "DOMAIN", "Computer vision", ["image recognition"]),
    ("ENT.DOMAIN.SECURITY", "DOMAIN", "Security domain", ["cybersecurity"]),
    ("ENT.DOMAIN.DEVOPS", "DOMAIN", "DevOps domain", ["cicd", "deployment"]),
    ("ENT.DOMAIN.DATABASE", "DOMAIN", "Database domain", ["sql", "nosql"]),
    ("ENT.DOMAIN.MESSAGING", "DOMAIN", "Messaging domain", ["chat", "email"]),
    ("ENT.DOMAIN.ANALYTICS", "DOMAIN", "Analytics domain", ["bi", "reporting"]),
    ("ENT.DOMAIN.AUTOMATION", "DOMAIN", "Automation domain", ["rpa", "scripting"]),
    # COMPONENT (10)
    ("ENT.COMPONENT.MODULE", "COMPONENT", "Software module", ["package", "library"]),
    ("ENT.COMPONENT.PLUGIN", "COMPONENT", "Plugin or extension", ["addon", "widget"]),
    ("ENT.COMPONENT.SDK", "COMPONENT", "Software development kit", ["toolkit", "library"]),
    ("ENT.COMPONENT.CLI", "COMPONENT", "Command line interface", ["terminal", "console"]),
    ("ENT.COMPONENT.GUI", "COMPONENT", "Graphical interface", ["ui", "frontend"]),
    ("ENT.COMPONENT.DRIVER", "COMPONENT", "Hardware or software driver", ["adapter"]),
    ("ENT.COMPONENT.MIDDLEWARE", "COMPONENT", "Middleware layer", ["interceptor"]),
    ("ENT.COMPONENT.RUNTIME", "COMPONENT", "Runtime environment", ["vm", "interpreter"]),
    ("ENT.COMPONENT.COMPILER", "COMPONENT", "Compiler or transpiler", ["builder"]),
    ("ENT.COMPONENT.DEBUGGER", "COMPONENT", "Debugging tool", ["inspector", "profiler"]),
]
for c in ENT:
    CONCEPTS.append(("ENT", c[0], c[1], c[2], c[3]))

# ===== ACT (200 concepts) =====
ACT = [
    # QUERY (20)
    ("ACT.QUERY.DATA", "QUERY", "Query for data or information", ["select", "get", "fetch"]),
    ("ACT.QUERY.STATUS", "QUERY", "Query status or state", ["check", "ping", "health"]),
    ("ACT.QUERY.SCHEMA", "QUERY", "Query schema or structure", ["describe", "schema"]),
    ("ACT.QUERY.COUNT", "QUERY", "Query count or quantity", ["count", "tally"]),
    ("ACT.QUERY.EXISTS", "QUERY", "Check if resource exists", ["exists", "has"]),
    ("ACT.QUERY.LIST", "QUERY", "List available items", ["enumerate", "browse"]),
    ("ACT.QUERY.SEARCH", "QUERY", "Search for matching items", ["find", "lookup"]),
    ("ACT.QUERY.FILTER", "QUERY", "Query with filters", ["where", "criteria"]),
    ("ACT.QUERY.METADATA", "QUERY", "Query metadata", ["info", "properties"]),
    ("ACT.QUERY.HISTORY", "QUERY", "Query historical data", ["log", "audit trail"]),
    ("ACT.QUERY.CAPABILITY", "QUERY", "Query agent capabilities", ["features", "support"]),
    ("ACT.QUERY.PERMISSION", "QUERY", "Query access permissions", ["rights", "roles"]),
    ("ACT.QUERY.VERSION", "QUERY", "Query version info", ["release", "build"]),
    ("ACT.QUERY.CONFIG", "QUERY", "Query configuration", ["settings", "preferences"]),
    ("ACT.QUERY.HEALTH", "QUERY", "Health check query", ["heartbeat", "alive"]),
    ("ACT.QUERY.STATS", "QUERY", "Query statistics", ["metrics", "counters"]),
    ("ACT.QUERY.DEPENDENCIES", "QUERY", "Query dependencies", ["requires", "needs"]),
    ("ACT.QUERY.RELATED", "QUERY", "Query related items", ["linked", "associated"]),
    ("ACT.QUERY.DIFF", "QUERY", "Query differences", ["compare", "delta"]),
    ("ACT.QUERY.PREVIEW", "QUERY", "Preview or dry-run query", ["simulate", "test"]),
    # ANALYZE (20)
    ("ACT.ANALYZE.SENTIMENT", "ANALYZE", "Analyze sentiment", ["emotion", "mood"]),
    ("ACT.ANALYZE.PATTERN", "ANALYZE", "Analyze patterns", ["trend", "correlation"]),
    ("ACT.ANALYZE.STATISTICS", "ANALYZE", "Statistical analysis", ["stats", "metrics"]),
    ("ACT.ANALYZE.CLASSIFY", "ANALYZE", "Classify or categorize", ["categorize", "label"]),
    ("ACT.ANALYZE.EXTRACT", "ANALYZE", "Extract information", ["parse", "mine"]),
    ("ACT.ANALYZE.CLUSTER", "ANALYZE", "Cluster data points", ["group", "segment"]),
    ("ACT.ANALYZE.PREDICT", "ANALYZE", "Predict outcomes", ["forecast", "project"]),
    ("ACT.ANALYZE.DETECT", "ANALYZE", "Detect anomalies", ["identify", "spot"]),
    ("ACT.ANALYZE.COMPARE", "ANALYZE", "Compare items", ["diff", "contrast"]),
    ("ACT.ANALYZE.RANK", "ANALYZE", "Rank or score items", ["rate", "prioritize"]),
    ("ACT.ANALYZE.PROFILE", "ANALYZE", "Profile performance", ["benchmark", "measure"]),
    ("ACT.ANALYZE.AUDIT", "ANALYZE", "Audit for compliance", ["review", "inspect"]),
    ("ACT.ANALYZE.DIAGNOSE", "ANALYZE", "Diagnose issues", ["troubleshoot", "debug"]),
    ("ACT.ANALYZE.EVALUATE", "ANALYZE", "Evaluate quality", ["assess", "grade"]),
    ("ACT.ANALYZE.CORRELATE", "ANALYZE", "Find correlations", ["relate", "link"]),
    ("ACT.ANALYZE.TOKENIZE", "ANALYZE", "Tokenize text", ["split", "segment"]),
    ("ACT.ANALYZE.EMBED", "ANALYZE", "Create embeddings", ["vectorize", "encode"]),
    ("ACT.ANALYZE.PARSE", "ANALYZE", "Parse structured data", ["interpret", "read"]),
    ("ACT.ANALYZE.VALIDATE", "ANALYZE", "Validate data quality", ["verify", "check"]),
    ("ACT.ANALYZE.SUMMARIZE", "ANALYZE", "Summarize analysis results", ["digest", "recap"]),
    # CREATE (20)
    ("ACT.CREATE.TEXT", "CREATE", "Generate text", ["write", "compose"]),
    ("ACT.CREATE.IMAGE", "CREATE", "Generate image", ["draw", "render"]),
    ("ACT.CREATE.RECORD", "CREATE", "Create database record", ["insert", "add"]),
    ("ACT.CREATE.FILE", "CREATE", "Create file", ["make", "generate"]),
    ("ACT.CREATE.SESSION", "CREATE", "Create session", ["open", "establish"]),
    ("ACT.CREATE.TOKEN", "CREATE", "Create auth token", ["issue", "generate"]),
    ("ACT.CREATE.USER", "CREATE", "Create user account", ["register", "signup"]),
    ("ACT.CREATE.CHANNEL", "CREATE", "Create comm channel", ["open", "establish"]),
    ("ACT.CREATE.TASK", "CREATE", "Create task or job", ["schedule", "queue"]),
    ("ACT.CREATE.EVENT", "CREATE", "Create event", ["emit", "trigger"]),
    ("ACT.CREATE.SNAPSHOT", "CREATE", "Create snapshot", ["checkpoint", "backup"]),
    ("ACT.CREATE.INDEX", "CREATE", "Create search index", ["build", "catalog"]),
    ("ACT.CREATE.REPORT", "CREATE", "Generate report", ["compile", "produce"]),
    ("ACT.CREATE.WORKFLOW", "CREATE", "Create workflow", ["define", "design"]),
    ("ACT.CREATE.RULE", "CREATE", "Create rule or policy", ["define", "set"]),
    ("ACT.CREATE.ALERT", "CREATE", "Create alert", ["set", "configure"]),
    ("ACT.CREATE.TEMPLATE", "CREATE", "Create template", ["design", "define"]),
    ("ACT.CREATE.COPY", "CREATE", "Create copy or clone", ["duplicate", "replicate"]),
    ("ACT.CREATE.LINK", "CREATE", "Create link or reference", ["connect", "associate"]),
    ("ACT.CREATE.BATCH", "CREATE", "Create batch of items", ["bulk create", "mass insert"]),
    # TRANSFORM (20)
    ("ACT.TRANSFORM.TRANSLATE", "TRANSFORM", "Translate languages", ["localize", "i18n"]),
    ("ACT.TRANSFORM.CONVERT", "TRANSFORM", "Convert format", ["change", "reformat"]),
    ("ACT.TRANSFORM.ENCODE", "TRANSFORM", "Encode data", ["serialize", "pack"]),
    ("ACT.TRANSFORM.DECODE", "TRANSFORM", "Decode data", ["deserialize", "unpack"]),
    ("ACT.TRANSFORM.SUMMARIZE", "TRANSFORM", "Summarize content", ["condense", "abstract"]),
    ("ACT.TRANSFORM.COMPRESS", "TRANSFORM", "Compress data", ["zip", "deflate"]),
    ("ACT.TRANSFORM.DECOMPRESS", "TRANSFORM", "Decompress data", ["unzip", "inflate"]),
    ("ACT.TRANSFORM.ENCRYPT", "TRANSFORM", "Encrypt data", ["cipher", "protect"]),
    ("ACT.TRANSFORM.DECRYPT", "TRANSFORM", "Decrypt data", ["decipher", "unlock"]),
    ("ACT.TRANSFORM.HASH", "TRANSFORM", "Hash data", ["digest", "checksum"]),
    ("ACT.TRANSFORM.NORMALIZE", "TRANSFORM", "Normalize data", ["standardize", "clean"]),
    ("ACT.TRANSFORM.DENORMALIZE", "TRANSFORM", "Denormalize data", ["flatten", "expand"]),
    ("ACT.TRANSFORM.MAP", "TRANSFORM", "Map data fields", ["project", "reshape"]),
    ("ACT.TRANSFORM.REDUCE", "TRANSFORM", "Reduce data set", ["aggregate", "fold"]),
    ("ACT.TRANSFORM.MERGE", "TRANSFORM", "Merge data sources", ["combine", "join"]),
    ("ACT.TRANSFORM.SPLIT", "TRANSFORM", "Split data", ["partition", "chunk"]),
    ("ACT.TRANSFORM.RESIZE", "TRANSFORM", "Resize content", ["scale", "crop"]),
    ("ACT.TRANSFORM.FORMAT", "TRANSFORM", "Format output", ["prettify", "render"]),
    ("ACT.TRANSFORM.ENRICH", "TRANSFORM", "Enrich with metadata", ["augment", "annotate"]),
    ("ACT.TRANSFORM.REDACT", "TRANSFORM", "Redact sensitive data", ["mask", "anonymize"]),
    # UPDATE (15)
    ("ACT.UPDATE.DATA", "UPDATE", "Update existing data", ["modify", "change"]),
    ("ACT.UPDATE.STATUS", "UPDATE", "Update status", ["set", "change"]),
    ("ACT.UPDATE.CONFIG", "UPDATE", "Update configuration", ["configure", "adjust"]),
    ("ACT.UPDATE.SCHEMA", "UPDATE", "Update schema", ["migrate", "alter"]),
    ("ACT.UPDATE.PERMISSION", "UPDATE", "Update permissions", ["grant", "revoke"]),
    ("ACT.UPDATE.METADATA", "UPDATE", "Update metadata", ["tag", "annotate"]),
    ("ACT.UPDATE.PRIORITY", "UPDATE", "Update priority", ["reprioritize", "escalate"]),
    ("ACT.UPDATE.STATE", "UPDATE", "Update state machine", ["transition", "advance"]),
    ("ACT.UPDATE.VERSION", "UPDATE", "Update version", ["upgrade", "bump"]),
    ("ACT.UPDATE.REPLACE", "UPDATE", "Replace entirely", ["swap", "substitute"]),
    ("ACT.UPDATE.PATCH", "UPDATE", "Partial update", ["patch", "amend"]),
    ("ACT.UPDATE.RENAME", "UPDATE", "Rename resource", ["alias", "relabel"]),
    ("ACT.UPDATE.MOVE", "UPDATE", "Move resource", ["relocate", "transfer"]),
    ("ACT.UPDATE.REORDER", "UPDATE", "Reorder items", ["rearrange", "sort"]),
    ("ACT.UPDATE.REFRESH", "UPDATE", "Refresh or reload", ["reload", "sync"]),
    # DELETE (10)
    ("ACT.DELETE.DATA", "DELETE", "Delete data or records", ["remove", "erase"]),
    ("ACT.DELETE.FILE", "DELETE", "Delete file", ["unlink", "destroy"]),
    ("ACT.DELETE.SESSION", "DELETE", "End session", ["close", "terminate"]),
    ("ACT.DELETE.TOKEN", "DELETE", "Revoke token", ["invalidate", "expire"]),
    ("ACT.DELETE.USER", "DELETE", "Delete user account", ["deactivate", "purge"]),
    ("ACT.DELETE.CACHE", "DELETE", "Clear cache", ["flush", "invalidate"]),
    ("ACT.DELETE.INDEX", "DELETE", "Drop index", ["remove", "destroy"]),
    ("ACT.DELETE.RULE", "DELETE", "Delete rule", ["remove", "disable"]),
    ("ACT.DELETE.LINK", "DELETE", "Remove link", ["unlink", "detach"]),
    ("ACT.DELETE.BATCH", "DELETE", "Batch delete", ["bulk remove", "purge"]),
    # PROCESS (20)
    ("ACT.PROCESS.BATCH", "PROCESS", "Process batch", ["bulk", "mass"]),
    ("ACT.PROCESS.STREAM", "PROCESS", "Process stream", ["flow", "pipe"]),
    ("ACT.PROCESS.VALIDATE", "PROCESS", "Validate data", ["verify", "check"]),
    ("ACT.PROCESS.FILTER", "PROCESS", "Filter data", ["select", "screen"]),
    ("ACT.PROCESS.SORT", "PROCESS", "Sort data", ["order", "arrange"]),
    ("ACT.PROCESS.AGGREGATE", "PROCESS", "Aggregate data", ["combine", "merge"]),
    ("ACT.PROCESS.DEDUPLICATE", "PROCESS", "Remove duplicates", ["distinct", "unique"]),
    ("ACT.PROCESS.ENQUEUE", "PROCESS", "Add to queue", ["push", "submit"]),
    ("ACT.PROCESS.DEQUEUE", "PROCESS", "Remove from queue", ["pop", "consume"]),
    ("ACT.PROCESS.PIPELINE", "PROCESS", "Execute pipeline", ["chain", "sequence"]),
    ("ACT.PROCESS.SCHEDULE", "PROCESS", "Schedule for later", ["defer", "delay"]),
    ("ACT.PROCESS.RETRY", "PROCESS", "Retry operation", ["reattempt", "repeat"]),
    ("ACT.PROCESS.ROLLBACK", "PROCESS", "Rollback operation", ["undo", "revert"]),
    ("ACT.PROCESS.COMMIT", "PROCESS", "Commit transaction", ["finalize", "confirm"]),
    ("ACT.PROCESS.CHECKPOINT", "PROCESS", "Save checkpoint", ["snapshot", "mark"]),
    ("ACT.PROCESS.RESUME", "PROCESS", "Resume processing", ["continue", "restart"]),
    ("ACT.PROCESS.PAUSE", "PROCESS", "Pause processing", ["suspend", "hold"]),
    ("ACT.PROCESS.CANCEL", "PROCESS", "Cancel operation", ["abort", "stop"]),
    ("ACT.PROCESS.EXECUTE", "PROCESS", "Execute command", ["run", "invoke"]),
    ("ACT.PROCESS.DISPATCH", "PROCESS", "Dispatch to handler", ["route", "forward"]),
    # COMMUNICATE (20)
    ("ACT.COMMUNICATE.SEND", "COMMUNICATE", "Send message", ["transmit", "deliver"]),
    ("ACT.COMMUNICATE.RECEIVE", "COMMUNICATE", "Receive message", ["accept", "get"]),
    ("ACT.COMMUNICATE.BROADCAST", "COMMUNICATE", "Broadcast to all", ["multicast", "publish"]),
    ("ACT.COMMUNICATE.SUBSCRIBE", "COMMUNICATE", "Subscribe to topic", ["listen", "follow"]),
    ("ACT.COMMUNICATE.UNSUBSCRIBE", "COMMUNICATE", "Unsubscribe from topic", ["unlisten", "unfollow"]),
    ("ACT.COMMUNICATE.PUBLISH", "COMMUNICATE", "Publish message", ["emit", "announce"]),
    ("ACT.COMMUNICATE.REQUEST", "COMMUNICATE", "Send request", ["ask", "invoke"]),
    ("ACT.COMMUNICATE.RESPOND", "COMMUNICATE", "Send response", ["reply", "answer"]),
    ("ACT.COMMUNICATE.ACKNOWLEDGE", "COMMUNICATE", "Acknowledge receipt", ["ack", "confirm"]),
    ("ACT.COMMUNICATE.NOTIFY", "COMMUNICATE", "Send notification", ["alert", "inform"]),
    ("ACT.COMMUNICATE.PING", "COMMUNICATE", "Ping for liveness", ["heartbeat", "check"]),
    ("ACT.COMMUNICATE.PONG", "COMMUNICATE", "Respond to ping", ["alive", "ok"]),
    ("ACT.COMMUNICATE.HANDSHAKE", "COMMUNICATE", "Protocol handshake", ["negotiate", "init"]),
    ("ACT.COMMUNICATE.SYNC", "COMMUNICATE", "Synchronize state", ["reconcile", "align"]),
    ("ACT.COMMUNICATE.STREAM", "COMMUNICATE", "Stream data", ["flow", "push"]),
    ("ACT.COMMUNICATE.NEGOTIATE", "COMMUNICATE", "Negotiate terms", ["agree", "settle"]),
    ("ACT.COMMUNICATE.REGISTER", "COMMUNICATE", "Register with service", ["enroll", "join"]),
    ("ACT.COMMUNICATE.DEREGISTER", "COMMUNICATE", "Deregister from service", ["leave", "quit"]),
    ("ACT.COMMUNICATE.FORWARD", "COMMUNICATE", "Forward message", ["relay", "proxy"]),
    ("ACT.COMMUNICATE.CALLBACK", "COMMUNICATE", "Callback notification", ["webhook", "hook"]),
    # CONTROL (20)
    ("ACT.CONTROL.START", "CONTROL", "Start process", ["begin", "launch"]),
    ("ACT.CONTROL.STOP", "CONTROL", "Stop process", ["halt", "terminate"]),
    ("ACT.CONTROL.RESTART", "CONTROL", "Restart process", ["reboot", "cycle"]),
    ("ACT.CONTROL.ENABLE", "CONTROL", "Enable feature", ["activate", "turn on"]),
    ("ACT.CONTROL.DISABLE", "CONTROL", "Disable feature", ["deactivate", "turn off"]),
    ("ACT.CONTROL.SCALE", "CONTROL", "Scale resources", ["resize", "adjust"]),
    ("ACT.CONTROL.DEPLOY", "CONTROL", "Deploy application", ["release", "ship"]),
    ("ACT.CONTROL.UNDEPLOY", "CONTROL", "Undeploy application", ["remove", "teardown"]),
    ("ACT.CONTROL.CONFIGURE", "CONTROL", "Configure system", ["setup", "tune"]),
    ("ACT.CONTROL.LOCK", "CONTROL", "Lock resource", ["acquire", "hold"]),
    ("ACT.CONTROL.UNLOCK", "CONTROL", "Unlock resource", ["release", "free"]),
    ("ACT.CONTROL.THROTTLE", "CONTROL", "Throttle rate", ["limit", "slow"]),
    ("ACT.CONTROL.MIGRATE", "CONTROL", "Migrate system", ["move", "transfer"]),
    ("ACT.CONTROL.BACKUP", "CONTROL", "Backup data", ["archive", "save"]),
    ("ACT.CONTROL.RESTORE", "CONTROL", "Restore from backup", ["recover", "unarchive"]),
    ("ACT.CONTROL.FAILOVER", "CONTROL", "Trigger failover", ["switchover", "fallback"]),
    ("ACT.CONTROL.PROMOTE", "CONTROL", "Promote replica", ["elevate", "upgrade"]),
    ("ACT.CONTROL.DEMOTE", "CONTROL", "Demote replica", ["downgrade", "relegate"]),
    ("ACT.CONTROL.DRAIN", "CONTROL", "Drain connections", ["evacuate", "empty"]),
    ("ACT.CONTROL.INITIALIZE", "CONTROL", "Initialize system", ["bootstrap", "setup"]),
    # SECURITY (20)
    ("ACT.SECURITY.AUTHENTICATE", "SECURITY", "Authenticate identity", ["login", "verify"]),
    ("ACT.SECURITY.AUTHORIZE", "SECURITY", "Authorize access", ["permit", "allow"]),
    ("ACT.SECURITY.SIGN", "SECURITY", "Sign data", ["seal", "stamp"]),
    ("ACT.SECURITY.VERIFY", "SECURITY", "Verify signature", ["validate", "check"]),
    ("ACT.SECURITY.ENCRYPT", "SECURITY", "Encrypt payload", ["protect", "cipher"]),
    ("ACT.SECURITY.DECRYPT", "SECURITY", "Decrypt payload", ["unlock", "decipher"]),
    ("ACT.SECURITY.REVOKE", "SECURITY", "Revoke access", ["deny", "block"]),
    ("ACT.SECURITY.ROTATE", "SECURITY", "Rotate credentials", ["renew", "refresh"]),
    ("ACT.SECURITY.AUDIT", "SECURITY", "Security audit", ["review", "inspect"]),
    ("ACT.SECURITY.SCAN", "SECURITY", "Security scan", ["check", "probe"]),
    ("ACT.SECURITY.BLOCK", "SECURITY", "Block access", ["deny", "reject"]),
    ("ACT.SECURITY.ALLOW", "SECURITY", "Allow access", ["permit", "whitelist"]),
    ("ACT.SECURITY.QUARANTINE", "SECURITY", "Quarantine threat", ["isolate", "sandbox"]),
    ("ACT.SECURITY.ESCALATE", "SECURITY", "Escalate privilege", ["elevate", "promote"]),
    ("ACT.SECURITY.DEESCALATE", "SECURITY", "Reduce privilege", ["demote", "restrict"]),
    ("ACT.SECURITY.LOG", "SECURITY", "Log security event", ["record", "trace"]),
    ("ACT.SECURITY.CHALLENGE", "SECURITY", "Issue challenge", ["test", "probe"]),
    ("ACT.SECURITY.TOKEN.REFRESH", "SECURITY", "Refresh auth token", ["renew", "extend"]),
    ("ACT.SECURITY.MFA", "SECURITY", "Multi-factor auth", ["2fa", "otp"]),
    ("ACT.SECURITY.LOGOUT", "SECURITY", "Terminate session", ["signout", "disconnect"]),
    # MANAGE (15)
    ("ACT.MANAGE.ASSIGN", "MANAGE", "Assign resource", ["allocate", "delegate"]),
    ("ACT.MANAGE.RELEASE", "MANAGE", "Release resource", ["free", "deallocate"]),
    ("ACT.MANAGE.MONITOR", "MANAGE", "Monitor resource", ["watch", "observe"]),
    ("ACT.MANAGE.ALERT", "MANAGE", "Raise alert", ["warn", "notify"]),
    ("ACT.MANAGE.HEAL", "MANAGE", "Self-heal system", ["repair", "fix"]),
    ("ACT.MANAGE.BALANCE", "MANAGE", "Balance load", ["distribute", "spread"]),
    ("ACT.MANAGE.OPTIMIZE", "MANAGE", "Optimize performance", ["tune", "improve"]),
    ("ACT.MANAGE.PROVISION", "MANAGE", "Provision resource", ["create", "setup"]),
    ("ACT.MANAGE.DEPROVISION", "MANAGE", "Remove resource", ["teardown", "destroy"]),
    ("ACT.MANAGE.REGISTER", "MANAGE", "Register service", ["enroll", "catalog"]),
    ("ACT.MANAGE.DISCOVER", "MANAGE", "Discover services", ["find", "locate"]),
    ("ACT.MANAGE.ORCHESTRATE", "MANAGE", "Orchestrate workflow", ["coordinate", "conduct"]),
    ("ACT.MANAGE.SCHEDULE", "MANAGE", "Schedule operation", ["plan", "queue"]),
    ("ACT.MANAGE.INVENTORY", "MANAGE", "Inventory resources", ["catalog", "list"]),
    ("ACT.MANAGE.REPORT", "MANAGE", "Generate mgmt report", ["summarize", "review"]),
    # RESPOND (10)
    ("ACT.RESPOND", "RESPOND", "Generic response", ["reply", "answer"]),
    ("ACT.RESPOND.SUCCESS", "RESPOND", "Success response", ["ok", "done"]),
    ("ACT.RESPOND.ERROR", "RESPOND", "Error response", ["fail", "reject"]),
    ("ACT.RESPOND.PARTIAL", "RESPOND", "Partial response", ["chunk", "page"]),
    ("ACT.RESPOND.REDIRECT", "RESPOND", "Redirect response", ["forward", "refer"]),
    ("ACT.RESPOND.ACCEPT", "RESPOND", "Accept request", ["approve", "allow"]),
    ("ACT.RESPOND.REJECT", "RESPOND", "Reject request", ["deny", "refuse"]),
    ("ACT.RESPOND.DEFER", "RESPOND", "Defer response", ["later", "pending"]),
    ("ACT.RESPOND.STREAM", "RESPOND", "Streaming response", ["chunked", "progressive"]),
    ("ACT.RESPOND.PAGINATE", "RESPOND", "Paginated response", ["page", "cursor"]),
    # LEARN (10)
    ("ACT.LEARN.TRAIN", "LEARN", "Train model", ["fit", "learn"]),
    ("ACT.LEARN.INFER", "LEARN", "Run inference", ["predict", "classify"]),
    ("ACT.LEARN.FINETUNE", "LEARN", "Fine-tune model", ["adapt", "specialize"]),
    ("ACT.LEARN.EVALUATE", "LEARN", "Evaluate model", ["test", "benchmark"]),
    ("ACT.LEARN.OPTIMIZE", "LEARN", "Optimize parameters", ["tune", "search"]),
    ("ACT.LEARN.GENERATE", "LEARN", "Generate output", ["produce", "create"]),
    ("ACT.LEARN.RETRIEVE", "LEARN", "Retrieve from knowledge", ["recall", "lookup"]),
    ("ACT.LEARN.REASON", "LEARN", "Logical reasoning", ["deduce", "conclude"]),
    ("ACT.LEARN.PLAN", "LEARN", "Plan actions", ["strategize", "design"]),
    ("ACT.LEARN.FEEDBACK", "LEARN", "Provide feedback", ["reward", "correct"]),
]
for c in ACT:
    CONCEPTS.append(("ACT", c[0], c[1], c[2], c[3]))

print(f"ENT: {len(ENT)}, ACT: {len(ACT)}")
print(f"Total so far: {len(CONCEPTS)}")
